objects/Budget__c.object
<CustomObject>
    <description>Targets for financial and service metrics for Super Centers.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether this budget is currently active. Utilized when multiple budgets share the same period.</description>
        <inlineHelpText>Denotes whether this budget is currently active.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The end day for this budget period.</description>
        <inlineHelpText>The end day for this budget period.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment_Gross_Actual__c</fullName>
        <defaultValue>00</defaultValue>
        <description>The amount of actual Equipment Gross dollars for this budget period.</description>
        <inlineHelpText>What is the current equipment gross profit?</inlineHelpText>
        <label>Equipment Gross Profit Actual</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Equipment_Revenue_Target__c</fullName>
        <description>The revenue target, in dollars, for this Super Center for the budget period. Specifically for Equipment revenue.</description>
        <inlineHelpText>What is the equipment revenue target?</inlineHelpText>
        <label>Equipment Revenue Target</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Period_Month__c</fullName>
        <description>The budget period month, represented by a two digit number - Example:
January = 01
October = 10</description>
        <inlineHelpText>The budget period month, represented by a two digit number - Example:
January = 01
October = 10</inlineHelpText>
        <label>Period Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period_Year__c</fullName>
        <description>The budget period year represented in a four digit number: 2015</description>
        <inlineHelpText>The budget period year represented in a four digit number: 2015</inlineHelpText>
        <label>Period Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>The segment to which the budget record is related to</description>
        <label>Segment</label>
        <referenceTo>Segment__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Average_Call_Revenue__c</fullName>
        <description>The service revenue average per call for this super center, per budget period. This is used to calculate total calls</description>
        <inlineHelpText>Defined by Operations</inlineHelpText>
        <label>Revenue Per Service Job Target</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Gross_Actual__c</fullName>
        <defaultValue>00</defaultValue>
        <description>The amount of actual Service Gross dollars during this budget period.</description>
        <inlineHelpText>What is the current service gross profit?</inlineHelpText>
        <label>Service Gross Profit Actual</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Gross_Target__c</fullName>
        <description>The Service dollars target for the parent super center during this budget&apos;s period.</description>
        <inlineHelpText>What is the current service gross profit target?</inlineHelpText>
        <label>Service Gross Profit Target</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Revenue_Actual__c</fullName>
        <description>The current Service Revenue actual for this budget period.</description>
        <inlineHelpText>What is the current service revenue?</inlineHelpText>
        <label>Service Revenue Actual</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Revenue_Target__c</fullName>
        <description>The target revenue, in dollars, for the related super center during this budget period.</description>
        <inlineHelpText>What is the service revenue target?</inlineHelpText>
        <label>Service Revenue Target</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The starting day of the month for this budget.</description>
        <inlineHelpText>The starting day for this budget period.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Super_Center__c</fullName>
        <description>This is the Super Center that this budget belongs to.</description>
        <inlineHelpText>This is the Super Center that this budget belongs to.</inlineHelpText>
        <label>Super Center</label>
        <referenceTo>Super_Center__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segment__c.object
<CustomObject>
    <description>A segment is a geographical division of a Super Center.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment_Name__c</fullName>
        <description>The specific name for the segment. Used pick-list not to rely on text field</description>
        <inlineHelpText>The specific name for the segment.</inlineHelpText>
        <label>Segment Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>El Paso</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Tallahassee</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>A Sure</fullName>
                </value>
                <value>
                    <fullName>Avondale</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Mesa</fullName>
                </value>
                <value>
                    <fullName>Tucson</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Waymar</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Miner-Equipment</fullName>
                </value>
                <value>
                    <fullName>Corpus Christi</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Super_Center__c</fullName>
        <description>The Super Center this Segment belongs to</description>
        <inlineHelpText>The Super Center this Segment belongs to</inlineHelpText>
        <label>Super Center</label>
        <referenceTo>Super_Center__c</referenceTo>
        <relationshipLabel>Segments</relationshipLabel>
        <relationshipName>Segments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Segment</label>
    <nameField>
        <label>Segment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Super_Center__c.object
<CustomObject>
    <description>Super Center is a branch service center that  contains the personnel and processes to sell and service customers for a specific geographical region.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>This is a picklist that should match up with the Location object (SVMXC__Site__c) to assist in assigning super center to work orders.</description>
        <inlineHelpText>This is a picklist that should match up with the Location object (SVMXC__Site__c) to assist in assigning super center to work orders.</inlineHelpText>
        <label>Segment</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Avondale</fullName>
                </value>
                <value>
                    <fullName>Corpus Christi</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>El Paso</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>Memphis</fullName>
                </value>
                <value>
                    <fullName>Mesa</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Miner-Equipment</fullName>
                </value>
                <value>
                    <fullName>Nashville</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>Tallahassee</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
                <value>
                    <fullName>Tucson</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>Waymar</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Super_Center__c</fullName>
        <description>This is a picklist that should match the values of the Super Center field on the Location object (SVMXC__Site__c). This is used for matching up Work Orders to Super Center.</description>
        <inlineHelpText>This is a picklist that should match the values of the Super Center field on the Location object (SVMXC__Site__c). This is used for matching up Work Orders to Super Center.</inlineHelpText>
        <label>Super_Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Miner-Atlanta</fullName>
                </value>
                <value>
                    <fullName>Miner-California</fullName>
                </value>
                <value>
                    <fullName>Miner-Central Texas</fullName>
                </value>
                <value>
                    <fullName>Miner-El Paso</fullName>
                </value>
                <value>
                    <fullName>Miner-Equipment</fullName>
                </value>
                <value>
                    <fullName>Miner-Florida</fullName>
                </value>
                <value>
                    <fullName>Miner-Houston</fullName>
                </value>
                <value>
                    <fullName>Miner-Miami</fullName>
                </value>
                <value>
                    <fullName>Miner-National</fullName>
                </value>
                <value>
                    <fullName>Miner-North Texas</fullName>
                </value>
                <value>
                    <fullName>Miner-Southwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Center</label>
    <nameField>
        <label>Super Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BatchBudgetUpdate_UT.cls
/**This class serves as unit test for the BatchBudgetUpdate class
***@Developer: Izay Ramos-Irizarry
***@Date:      8/1/2015
***@Version:   1.0
*/
@isTest(SeeAllData=true)
public class BatchBudgetUpdate_UT {
    
    public static TestMethod void test1(){
        //Get budget Record Types
        List<RecordType> budgetRecTypes = [SELECT Id FROM RecordType WHERE SObjectType = 'Budget__c'];
        //Need a super center
        Super_Center__c sc = new Super_Center__c();
        sc.Name = 'Miner-Central Texas';
        sc.Super_Center__c = 'Miner-Central Texas';
        insert sc;
        //Need a segment
        Segment__c seg = new Segment__c();
        seg.Super_Center__c = sc.Id;
        seg.Name = 'San Antonio';
        seg.Segment_Name__c = 'San Antonio';
        insert seg;
        //Need three budget record for the super center for the past three months
        //Need start and end date for the budget
        Date startOfMonth = Date.today().toStartOfMonth();
        Date endOfMonth = startOfMonth.addMonths(1).toStartOfMonth() - 1;
        //The first budget
        Budget__c b1 = new Budget__c();
        b1.Name = 'This Month';
        b1.Active__c = true;
        b1.Start_Date__c = startOfMonth;
        b1.End_Date__c = endOfMonth;
        b1.Super_Center__c = sc.Id;
        b1.Equipment_Revenue_Target__c = 0; 
        b1.Service_Average_Call_Revenue__c = 0; 
        b1.Service_Gross_Target__c = 0;
        b1.Service_Revenue_Target__c = 0;
        b1.RecordTypeId = budgetRecTypes[0].Id;
        b1.Segment__c = seg.Id;
        insert b1;
        //Need to change start and end date for new budget
        startOfMonth = startOfMonth.addMonths(-1);
        endOfMonth = startOfMonth.addMonths(1).toStartOfMonth() - 1;
        //The second budget
        Budget__c b2 = new Budget__c();
        b2.Name = 'Last Month';
        b2.Active__c = true;
        b2.Start_Date__c = startOfMonth;
        b2.End_Date__c = endOfMonth;
        b2.Super_Center__c = sc.Id;
        b2.Segment__c = seg.Id;
        b2.Equipment_Revenue_Target__c = 0; 
        b2.Service_Average_Call_Revenue__c = 0; 
        b2.Service_Gross_Target__c = 0;
        b2.Service_Revenue_Target__c = 0;
        b2.RecordTypeId = budgetRecTypes[1].Id;
        insert b2;
        //Need to change start and end date for the new budget
        startOfMonth = startOfMonth.addMonths(-1);
        endOfMonth = startOfMonth.addMonths(1).toStartOfMonth() - 1;
        //the third budget
        Budget__c b3 = new Budget__c();
        b3.Name = 'Month Before Last';
        b3.Active__c = true;
        b3.Start_Date__c = startOfMonth;
        b3.End_Date__c = endOfMonth;
        b3.Super_Center__c = sc.Id;
        b3.Segment__c = seg.Id;
        b3.Equipment_Revenue_Target__c = 0; 
        b3.Service_Average_Call_Revenue__c = 0; 
        b3.Service_Gross_Target__c = 0;
        b3.Service_Revenue_Target__c = 0;
        insert b3;
        Test.startTest();
        BatchBudgetUpdate b = new BatchBudgetUpdate();
        b.query = 'SELECT Id,Name,Service_Revenue_Actual__c,Service_Gross_Actual__c,Period_Month__c,Period_Year__c,End_Date__c,Start_Date__c,Active__c,Equipment_Gross_Actual__c,Equipment_Revenue_Actual__c,' +
                'Equipment_Call_Volume_Actual__c,Equipment_Scheduled_Call_Volume_Actual__c,Equipment_Invoiced_Call_Volume_Actual__c,Service_Gross_Profit_Opportunity_Dollars__c,'+
                'Service_Revenue_Opportunity_Dollars__c,Equipment_Revenue_Opportunity_Dollars__c,Equipment_Gross_Profit_Opportunity__c,'+
                'Service_Call_Volume_Actual__c,Service_Scheduled_Call_Volume_Actual__c,Service_Invoiced_Call_Volume_Actual__c,Super_Center__c,Super_Center__r.Name,' +
                'Super_Center__r.Super_Center__c,Super_Center__r.Segment__c,Segment__c,Segment__r.Segment_Name__c,RecordTypeId' +
                ' FROM Budget__c WHERE (Start_Date__c >= LAST_YEAR AND End_Date__c <= THIS_YEAR) AND Active__c = TRUE' +
                ' ORDER BY CreatedDate DESC, Super_Center__r.Name DESC, Start_Date__c ASC LIMIT 3';
        Database.executeBatch(b);
        Test.stopTest();
    }
    
    public static TestMethod void test3(){
        BatchBudgetUpdate_Scheduler scheduler = new BatchBudgetUpdate_Scheduler();
        scheduler.b.query = 'SELECT Id,Name,Service_Revenue_Actual__c,Service_Gross_Actual__c,Period_Month__c,Period_Year__c,End_Date__c,Start_Date__c,Active__c,Equipment_Gross_Actual__c,Equipment_Revenue_Actual__c,' +
                'Equipment_Call_Volume_Actual__c,Equipment_Scheduled_Call_Volume_Actual__c,Equipment_Invoiced_Call_Volume_Actual__c,Service_Gross_Profit_Opportunity_Dollars__c,'+
                'Service_Revenue_Opportunity_Dollars__c,Equipment_Revenue_Opportunity_Dollars__c,Equipment_Gross_Profit_Opportunity__c,'+
                'Service_Call_Volume_Actual__c,Service_Scheduled_Call_Volume_Actual__c,Service_Invoiced_Call_Volume_Actual__c,Super_Center__c,Super_Center__r.Name,' +
                'Super_Center__r.Super_Center__c,Super_Center__r.Segment__c,Segment__c,Segment__r.Segment_Name__c,RecordTypeId' +
                ' FROM Budget__c WHERE (Start_Date__c >= LAST_YEAR AND End_Date__c <= THIS_YEAR) AND Active__c = TRUE' +
                ' ORDER BY Super_Center__r.Name DESC, Start_Date__c ASC LIMIT 3';
        String sch = '20 30 8 10 2 ?';
        Test.startTest();
        String jobID = system.schedule('Service Report Tracker Job', sch, scheduler);
        Test.stopTest();
    }
    
}