objects/Default_Invoice_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default status for invoices when Avatax returns successful</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status to be set on invoice when tax is returned successful</description>
        <inlineHelpText>Status to be set on invoice when tax is returned successful</inlineHelpText>
        <label>Status</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Default Invoice Status</label>
</CustomObject>

objects/Key_Value_Store__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Storage for key values referenced by code and formulas within solution</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Return value for the associated key</description>
        <inlineHelpText>Enter the value to be returned for the associated key</inlineHelpText>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Key Value Store</label>
</CustomObject>

objects/MH_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Calibration</fullName>
                </value>
                <value>
                    <fullName>Cleanup</fullName>
                </value>
                <value>
                    <fullName>Installation</fullName>
                </value>
                <value>
                    <fullName>Repair</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Certificate__c</fullName>
        <description>Sales Tax certificate value from the work order. Passed to Avatax to indicate that the work is non-taxable.</description>
        <formula>Work_Order__r.Certificate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Tax Certificate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <label>Date Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>SVMXC__Site__c</referenceTo>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Segment__c</fullName>
        <description>Used to hold the segment that the work order is related to. Because the segment can come from either the technician&gt;Sales Team or the Sales Team fields on the work order, it is easier for integration purposes to set the values here when creating an invoice</description>
        <label>Segment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for integration (depends on tax details).</description>
        <inlineHelpText>Status for integration (depends on tax details).</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Billed</fullName>
                    <default>true</default>
                    <label>Not Billed</label>
                </value>
                <value>
                    <fullName>In-Batch</fullName>
                </value>
                <value>
                    <fullName>Billed</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Work Order this invoice was created from.</description>
        <label>Work Order</label>
        <referenceTo>SVMXC__Service_Order__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MH_Invoice_Details__c.object
<CustomObject>
    <description>Invoice details to support WO / WD creation
Proof of Concept 12/23/13</description>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Destination Credit</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
                <value>
                    <fullName>Sublbr - New Construction</fullName>
                </value>
                <value>
                    <fullName>Standard Labor</fullName>
                </value>
                <value>
                    <fullName>Double Time Labor</fullName>
                </value>
                <value>
                    <fullName>Pass Through Tax</fullName>
                </value>
                <value>
                    <fullName>Field Supplies</fullName>
                </value>
                <value>
                    <fullName>Freight - New Construction</fullName>
                </value>
                <value>
                    <fullName>Freight - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Parts - New Construction</fullName>
                </value>
                <value>
                    <fullName>Parts - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Preventive Maintenance</fullName>
                </value>
                <value>
                    <fullName>Rental - New Construction</fullName>
                </value>
                <value>
                    <fullName>Rental - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Sublbr - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Pass Through Parts</fullName>
                </value>
                <value>
                    <fullName>Pass Through Labor</fullName>
                </value>
                <value>
                    <fullName>Pass Through Freight</fullName>
                </value>
                <value>
                    <fullName>Pass Through Rentals</fullName>
                </value>
                <value>
                    <fullName>Overtime Labor</fullName>
                </value>
                <value>
                    <fullName>Asset Mgmt Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <label>Date Invoiced</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>MH-Invoice</label>
        <referenceTo>MH_Invoice__c</referenceTo>
        <relationshipName>Invoice_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Line_Qty__c</fullName>
        <label>Line Qty</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Line_Price__c</fullName>
        <description>The detail line-item line price</description>
        <label>Extended Price</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>SVMXC__Service_Order__c</referenceTo>
        <relationshipName>Invoice_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Invoice Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tax_Code_Associations__c.object
<CustomObject>
    <description>Allows associating tax codes with activity types from work orders. For each activity type, one and only one tax code should be set. This value is passed via integration to Avatax for calculation of sales tax.</description>
    <fields>
        <fullName>Segment__c</fullName>
        <description>Denotes that the rule is segment specific to support multiple tax codes per activity type based on segments (Service Teams)</description>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>Valley</fullName>
                </value>
                <value>
                    <fullName>El Paso</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>New Orleans</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Jacksonville</fullName>
                </value>
                <value>
                    <fullName>Orlando</fullName>
                </value>
                <value>
                    <fullName>Tallahassee</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Avondale</fullName>
                </value>
                <value>
                    <fullName>Mesa</fullName>
                </value>
                <value>
                    <fullName>Tucson</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Miner-Equipment</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax Code Association</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Tax Code Associations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Code Associations</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <description>Exceptions to Tax Code Association</description>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/callAvataxInvoice.cls
public with sharing class callAvataxInvoice {

	public List<MH_Invoice_Details__c> invlist;
	public String oname {get;set;}
	public String otype {get;set;}
	public String tcode {get;set;}
	public Integer x {get;set;}
	public Integer y {get;set;}
	public String invid;
	public String SampleResult {get;set;}
	public Boolean error1 {get;set;}
	public Boolean showconf {get;set;}
	
	public callAvataxInvoice(){
		
	}
    
	public callAvataxInvoice(ApexPages.StandardController controller){
		
	}
    
	public pageReference call(){
		
		invid = ApexPages.CurrentPage().getParameters().get('id');
		showconf = true;
		
		List<Key_Value_Store__c> kvslist = new List<Key_Value_Store__c>();
		kvslist = [SELECT Id, Name, Value__c FROM Key_Value_Store__c];
		
		List<Default_Invoice_Status__c> statuslist = new List<Default_Invoice_Status__c>();
		statuslist = [SELECT Id, Name, Status__c FROM Default_Invoice_Status__c];
		Map<String, String> statusmap = new Map<String, String>();
		for (Default_Invoice_Status__c index : statuslist)
			statusmap.put(index.Name.toLowerCase(), index.Status__c);
		
		String user = null;
		String pass = null;
		for(Key_Value_Store__c kvsindex : kvslist){
			if (kvsindex.Name.toLowerCase() == 'avatax account id')
				user = kvsindex.Value__c;
			if (kvsindex.Name.toLowerCase() == 'avatax license key')
				pass = kvsindex.Value__c;
		}
		
		MH_Invoice__c inv = [SELECT Id, Name, Work_Order__r.SVMXC__Group_Member__c, Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.Company_Code__c, Certificate__c, Date_Invoiced__c,
		          			 Work_Order__r.SVMXC__Service_Group__c, Work_Order__r.SVMXC__Service_Group__r.Company_Code__c, Work_Order__c, Work_Order__r.SVMXC__Company__c, Work_Order__r.SVMXC__Company__r.MH_SL_CustID__c,
		          			 Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__c, Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__Street__c, Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__City__c,
		          			 Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__State__c, Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__Zip__c, Work_Order__r.SVMXC__Service_Group__r.SVMXC__Street__c,
		          			 Work_Order__r.SVMXC__Service_Group__r.SVMXC__City__c, Work_Order__r.SVMXC__Service_Group__r.SVMXC__State__c, Work_Order__r.SVMXC__Service_Group__r.SVMXC__Zip__c, Work_Order__r.Location__c,
		          			 Work_Order__r.Location__r.SVMXC__Street__c, Work_Order__r.Location__r.SVMXC__City__c, Work_Order__r.Location__r.SVMXC__State__c, Work_Order__r.Location__r.SVMXC__Zip__c, Work_Order__r.Business_Unit__c,
                             Work_Order__r.Segment__r.Segment_Name__c, Work_Order__r.SVMXC__Order_Type__c FROM MH_Invoice__c WHERE Id =: invid];
		
		invlist = new List<MH_Invoice_Details__c>();
		invlist = [SELECT Id, Name, Total_Line_Price__c, Line_Qty__c, Sales_Tax__c, Activity_Type__c, Line_Type__c,Work_Detail__c,Work_Detail__r.Tax_Code__c  FROM MH_Invoice_Details__c WHERE Invoice__c =: inv.Id];
		
		avataxAvalaraComServicesAlt.TaxSvcAltSecSoap taxSvc = new avataxAvalaraComServicesAlt.TaxSvcAltSecSoap();
		taxSvc.Security = new avataxAvalaraComServicesAlt.Security();
		taxSvc.Security.UsernameToken = new avataxAvalaraComServicesAlt.UsernameToken_element();
		taxSvc.Security.UsernameToken.Username = user;
		taxSvc.Security.UsernameToken.Password = pass;
		taxSvc.Profile = new avataxAvalaraComServicesAlt.Profile();
		taxSvc.Profile.Name = '1.0.0';
		taxSvc.Profile.Client = 'My Application Name,1.0';
		taxSvc.Profile.Machine = 'My Machine Name';
		
		avataxAvalaraComServicesAlt.GetTaxRequest gtreq = new avataxAvalaraComServicesAlt.GetTaxRequest();
		error1 = false;
		if(String.isNotBlank(inv.Work_Order__c)){
			if(String.IsNotBlank(inv.Work_Order__r.SVMXC__Group_Member__c)){
				if(inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__c != null)
					gtreq.CompanyCode = inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.Company_Code__c;
			}else{
				if(inv.Work_Order__r.SVMXC__Service_Group__c != null)
					gtreq.CompanyCode = inv.Work_Order__r.SVMXC__Service_Group__r.Company_Code__c;
			}
		}
        if(String.isBlank(gtreq.CompanyCode ))
            error1 = true;
		
		gtreq.DocType = 'SalesInvoice';
		gtreq.DocCode = inv.Name;
        gtreq.ReferenceCode = inv.Id;
		if(inv.Work_Order__c != null){
			if(inv.Work_Order__r.SVMXC__Company__c != null)
				gtreq.CustomerCode = inv.Work_Order__r.SVMXC__Company__r.MH_SL_CustID__c;
		}
		gtreq.Discount = 0; 
		gtreq.DetailLevel = 'Tax';
		gtreq.HashCode = 0;
		gtreq.ServiceMode = 'Automatic';
		gtreq.ExchangeRate = 0;
		gtreq.ExchangeRateEffDate = date.today();
		gtreq.PaymentDate = date.today();
        gtreq.DocDate = inv.Date_Invoiced__c;
        gtreq.ExemptionNo = inv.Certificate__c;
		
		avataxAvalaraComServicesAlt.BaseAddress orgAddr = new avataxAvalaraComServicesAlt.BaseAddress();
		orgAddr.AddressCode = 'Origin';
		if(inv.Work_Order__c != null){
			if(inv.Work_Order__r.SVMXC__Group_Member__c != null){
				if(inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__c != null){
					orgAddr.Line1 = inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__Street__c;//'11827 Tech Com Dr #115';//w.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__Street__c;
					orgAddr.City = inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__City__c;//'San Antonio'; //
					orgAddr.Region = inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__State__c;//'TX'; //
					orgAddr.PostalCode = inv.Work_Order__r.SVMXC__Group_Member__r.SVMXC__Service_Group__r.SVMXC__Zip__c;//'78233'; //
				}
			}else{
				if (inv.Work_Order__r.SVMXC__Service_Group__c != null){
					orgAddr.Line1 = inv.Work_Order__r.SVMXC__Service_Group__r.SVMXC__Street__c;
					orgAddr.City = inv.Work_Order__r.SVMXC__Service_Group__r.SVMXC__City__c;
					orgAddr.Region = inv.Work_Order__r.SVMXC__Service_Group__r.SVMXC__State__c;
					orgAddr.PostalCode = inv.Work_Order__r.SVMXC__Service_Group__r.SVMXC__Zip__c;
				}
			}
		}
		
		orgAddr.TaxRegionId = 0;
		avataxAvalaraComServicesAlt.BaseAddress dstAddr = new avataxAvalaraComServicesAlt.BaseAddress();
		dstAddr.AddressCode = 'Destination';
		if(String.isNotBlank(inv.Work_Order__c)){
			if(String.isNotBlank(inv.Work_Order__r.Location__c)){
				dstAddr.Line1 = inv.Work_Order__r.Location__r.SVMXC__Street__c;//'11827 Tech Com Dr #116'; 
				dstAddr.City = inv.Work_Order__r.Location__r.SVMXC__City__c;//'San Antonio'; 
				dstAddr.Region = inv.Work_Order__r.Location__r.SVMXC__State__c;//'TX'; 
				dstAddr.PostalCode = inv.Work_Order__r.Location__r.SVMXC__Zip__c;//'78233'; 
			}
		}
		dstAddr.TaxRegionId = 0;
		
		gtreq.Addresses = new avataxAvalaraComServicesAlt.ArrayOfBaseAddress();
		gtreq.Addresses.BaseAddress = new avataxAvalaraComServicesAlt.BaseAddress[2];
		
		gtreq.Addresses.BaseAddress[0] = orgAddr;
		gtreq.Addresses.BaseAddress[1] = dstAddr;
		
		gtreq.OriginCode = orgAddr.AddressCode;
		gtreq.DestinationCode = dstAddr.AddressCode;
		
		gtreq.Lines = new avataxAvalaraComServicesAlt.ArrayOfLine();
		gtreq.Lines.Line = new avataxAvalaraComServicesAlt.Line[invlist.size()];
		Integer i = 0;
		
        //Tax Code Association Rule
		x = 0;
		y = 0;
		Map<String, MH_Invoice_Details__c> detailmap = new Map<String, MH_Invoice_Details__c>();
        Map<Id,SVMXC__Service_Order_Line__c> workDetMap = new Map<Id,SVMXC__Service_Order_Line__c>();
        //Need to check if the all work detail lines have tax code associated with them
        Boolean needCode = false;
        for(MH_Invoice_Details__c line : invlist){
            if(String.isBlank(line.Work_Detail__r.Tax_Code__c)){
                needCode = true;
                break;
            }
        }
        if(needCode){
            List<SVMXC__Service_Order_Line__c> tempList = CallAvatax.getTaxCode(inv.Work_Order__c);
            for(SVMXC__Service_Order_Line__c line :tempList){
                workDetMap.put(line.Id,line);
            }
            tempList.clear();
        }
		if(!error1){
			for(MH_Invoice_Details__c invindex : invlist){
				detailmap.put(invindex.Name, invindex);
				gtreq.Lines.Line[i] = new avataxAvalaraComServicesAlt.Line();
				gtreq.Lines.Line[i].No = invindex.Name;
				gtreq.Lines.Line[i].Amount = (invindex.Total_Line_Price__c != null) ? invindex.Total_Line_Price__c : 0;
				gtreq.Lines.Line[i].Qty = (invindex.Line_Qty__c != null) ? invindex.Line_Qty__c : 0;
				gtreq.Lines.Line[i].Discounted = false;
				gtreq.Lines.Line[i].OriginCode = 'Origin';
				gtreq.Lines.Line[i].DestinationCode = 'Destination';
                gtreq.Lines.Line[i].ItemCode = invindex.Activity_Type__c;
				if(String.isBlank(invindex.Activity_Type__c)){
					y = 1;
					oname = invindex.Name;
					break;
				}
                String taxCode = '';
                if(needCode)
                    taxCode = workDetMap.get(invindex.Work_Detail__c).Tax_Code__c;
                else
                	taxCode = invindex.Work_Detail__r.Tax_Code__c;//CallAvatax.getTaxCode(inv.Work_Order__r.Segment__r.Segment_Name__c, inv.Work_Order__r.SVMXC__Order_Type__c,invindex.Activity_Type__c,invindex.Line_Type__c);
				if(String.isNotBlank(taxCode))
					gtreq.Lines.Line[i].TaxCode = taxCode;
				else{
					x = 1;
					oname = invindex.Name;
					otype = invindex.Activity_Type__c;
					break;
				}
				i++;
			}
		}
		//gtreq.DocDate = Date.Today();
		gtreq.Commit_x=false;
		
		avataxAvalaraComServicesAlt.GetTaxResult gtres = null;
		SampleResult = '';
		
		if((x == 0) && (y == 0) && (!error1)){
			try{
			     gtres = taxSvc.GetTax(gtreq);
			
			     if(gtres.ResultCode == 'Success'){
			         SampleResult = '<span class="success-result">'+gtres.ResultCode + '</span>' +
                         '<table class="message-table"><tr><th>Total Tax</th><td>' + gtres.TotalTax + '</td></tr></table>';
			         showconf = false;
			     }else{
			         SampleResult = '<span class="error-result">'+gtres.ResultCode + '</span><table class="message-table"><tr><th>Summary</th><td>' + ((gtres.Messages != null) ? gtres.Messages.Message[0].Summary : 'Not available') + '</td></tr>';
                     SampleResult += '<tr><th>Details</th><td>'+ ((gtres.Messages != null) ? gtres.Messages.Message[0].Details: 'Not available') +'</td></tr>';
                     SampleResult += '<tr><th>Refers To</th><td>'+ ((gtres.Messages != null) ? gtres.Messages.Message[0].RefersTo: 'Not available') +'</td></tr>';
                     SampleResult += '<tr><th>Source</th><td>'+ ((gtres.Messages != null) ? gtres.Messages.Message[0].Source: 'Not available') +'</td></tr>';
                     SampleResult += '</table>';
                     showconf = true;
			     }
			}catch(Exception ex){
			     SampleResult = 'GetTax Threw an Exception: ' + ex.getmessage();
			}
		}
		
		if((gtres != null)){
			//gtres.TaxLines = new avataxavalaraComServicesAlt.ArrayOfTaxLine();
			//gtres.TaxLines.TaxLine = new avataxavalaraComServicesAlt.TaxLine();
			if((gtres.TaxLines != null)){
				if((gtres.TaxLines.TaxLine != null)){
					if(String.isNotBlank(inv.Work_Order__c)){
						if(!showconf){
							if((String.isBlank(inv.Work_Order__r.Business_Unit__c)) || (!statusmap.containsKey(inv.Work_Order__r.Business_Unit__c.toLowerCase()))){
								SampleResult = 'There is no invoice status set for the business unit, please select the appropriate invoice status';
								showconf = true;
							}else
								inv.Status__c = statusmap.get(inv.Work_Order__r.Business_Unit__c.toLowerCase());
						}else{
							if((String.isBlank(inv.Work_Order__r.Business_Unit__c)) || ((!statusmap.containsKey((inv.Work_Order__r.Business_Unit__c + '-Error').toLowerCase())) && (!statusmap.containsKey((inv.Work_Order__r.Business_Unit__c + ' - Error').toLowerCase()))))
								inv.Status__c = 'Error';
							else{
								if(statusmap.containsKey((inv.Work_Order__r.Business_Unit__c + '-Error').toLowerCase()))
									inv.Status__c = statusmap.get((inv.Work_Order__r.Business_Unit__c + '-Error').toLowerCase());
								if(statusmap.containsKey((inv.Work_Order__r.Business_Unit__c + ' - Error').toLowerCase()))
									inv.Status__c = statusmap.get((inv.Work_Order__r.Business_Unit__c + ' - Error').toLowerCase());
							}
						}
					}
					List<MH_Invoice_Details__c> detaillist = new List<MH_Invoice_Details__c>();
                    for(avataxavalaraComServicesAlt.TaxLine tl : gtres.TaxLines.TaxLine){
                        if(detailmap.containsKey(tl.No)){
                            detailmap.get(tl.No).Sales_Tax__c = tl.Tax;
                            detaillist.add(detailmap.get(tl.No));
                        }
                    }
					update detaillist;
                    update inv;
                    if(needCode)
                        update workDetMap.values();
				}
			}
		}
		if(!showconf){
			PageReference page = new PageReference('/' + invid);
	        page.setRedirect(true);
	        return page;
		}
		return null;
	}
	
	public pageReference Save(){
		
		if ((tcode != null) && (tcode != '')){
			Tax_Code_Associations__c t = new Tax_Code_Associations__c (Activity_Type__c = otype, Tax_Code__c = tcode);
			insert t;
		}
		else{
			 ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter a tax code.'));
             return null;
		}
		pageReference pr = new pageReference('/' + invid);
		return pr;
		
	}
	
	public pageReference Cancel(){
		
		pageReference pr = new pageReference('/' + invid);
		return pr;
		
	}
	
}