objects/Report_Export_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the settings for report export</description>
    <fields>
        <fullName>Attachment_File_Name__c</fullName>
        <label>Attachment File Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>This is the attachment format.  
application/vnd.ms-excel for excel file (default)
text/csv for csv file</description>
        <label>Content Type</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <description>Optional plain text that goes to the email&apos;s body</description>
        <label>Email Body</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Recipient__c</fullName>
        <description>Email recipient</description>
        <label>Email Recipient</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Subject__c</fullName>
        <description>Subject of the email</description>
        <label>Email Subject</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Report Export Settings</label>
</CustomObject>

classes/UNITY_ReportExporter.cls
global class UNITY_ReportExporter implements System.Schedulable {
    public String reportName {get; set;}
    
    public UNITY_ReportExporter(String reportName){
        this.reportName = reportName;
    }
    global void execute(SchedulableContext sc) {
        DoExport(reportName);        
    }
    @future(callout=true)
    public static void DoExport(String reportName){
        //Retrieve report details
        List<Report> reportList = [SELECT Id, Name FROM Report WHERE Name = :reportName];
        system.debug('@@@DoExport reportList'+reportList);
        if (reportList.size() <= 0)
            return;
        //Retrieve custom report setting
        Report_Export_Settings__c reportSetting = Report_Export_Settings__c.getValues(reportName);
        system.debug('@@@DoExport reportSetting'+reportSetting);
        if (reportList.size() > 0 && reportSetting != null){
            ApexPages.PageReference report = new ApexPages.PageReference('/' + reportList[0].Id + '?export=1&enc=UTF-8&xf=csv');
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFileName(reportSetting.Attachment_File_Name__c);
            attachment.setBody(report.getContent());
            attachment.setContentType(reportSetting.Content_Type__c);
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment } );
            message.setSubject(reportSetting.Email_Subject__c);
            String body = reportSetting.Email_Body__c == null ? String.valueof(Date.today()) : reportSetting.Email_Body__c + DateTime.now();
            message.setPlainTextBody(body);
            message.setToAddresses( new String[] { reportSetting.Email_Recipient__c } );
            Messaging.SendEmailResult[] sendEmailResult = Messaging.sendEmail( new Messaging.SingleEmailMessage[] { message } );            
            system.debug('@@@DoExport sendEmailResult'+sendEmailResult);
        }
    }
}