objects/UNITY_Attachment__c.object
<CustomObject>
    <description>UNITY Attachment object</description>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Check Request Form</fullName>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>Miner Sign Off Sheet</fullName>
                </value>
                <value>
                    <fullName>Note To Biller</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty Information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>Atch-{0000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_General_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting for general kay value mappings for the App</description>
    <fields>
        <fullName>UNITY_Description__c</fullName>
        <description>Description for this setting&apos;s usage</description>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UNITY_Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UNITY General Settings</label>
</CustomObject>

objects/UNITY_Invoice__c.object
<CustomObject>
    <description>UNITY Invoice object</description>
    <fields>
        <fullName>UNITY_Customer_Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Contract of Customer. Should be copied from the Case.</description>
        <label>UNITY_Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Missing_Required_Documentation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Missing Required Documentation</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Required_Documentation__c</fullName>
        <label>Required Documentation</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Check Request Form</fullName>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_OrderMainTest.cls
/*------------------------------------------------------------
Name:          UNITY_OrderMainTest
Author:        Krishna Kameneni
Company:       Minor
Description:   This class contains unit tests for validating the behavior of trigger UNITY_OrderMain
History:
01/28/2016     Krishna Kameneni(Perficient)    Added/Modified comments
,Indentation 
Added test method
------------------------------------------------------------*/
//@isTest(SeeAllData=true)
@isTest
private class UNITY_OrderMainTest{
    //Setup Product and Pricebook Info
    public static Id PRICEBOOKENTRYID_T;
    public static Id PRICEBOOKENTRYID_L;
    public static Id PRICEBOOKENTRYID_P;
    public static Id PRODUCTID;
    static{
        //Create Product & pricebook
        Map<String,String> prodMapP = TestDataProvider.getProductAndPriceBookEntry(1,'Part');
        for(String s :prodMapP.keySet()){
            PRICEBOOKENTRYID_P = (Id)prodMapP.get(s);
            PRODUCTID = (Id)s;
        }
        Map<String,String> prodMapL = TestDataProvider.getProductAndPriceBookEntry(1,'Labor');
        for(String s :prodMapL.keySet()){
            PRICEBOOKENTRYID_L = (Id)prodMapL.get(s);
        }
        Map<String,String> prodMapT = TestDataProvider.getProductAndPriceBookEntry(1,'Travel');
        for(String s :prodMapT.keySet()){
            PRICEBOOKENTRYID_T = (Id)prodMapT.get(s);
        }
    }
    static testMethod void updateMissingRequiredDocumentation(){
        //Miner Test Data Set up
        TestDataProvider.setKeyValueStore();
        
        List<UNITY_General_Settings__c> generalSetting =new  List<UNITY_General_Settings__c>();
        system.debug(UNITY_General_Settings__c.getAll().values());
        if(UNITY_General_Settings__c.getAll().values()==null){
            
        
            UNITY_General_Settings__c setting1 = new UNITY_General_Settings__c(
                Name = 'Service Fee POLI Activity Type',
                UNITY_Description__c = 'Vendor Service Fee POLI Activity Type',
                UNITY_Value__c = 'Vendor Service Fee'
            );
            
            UNITY_General_Settings__c setting2 = new UNITY_General_Settings__c(
                Name = 'Service Fee POLI Type',
                UNITY_Description__c = 'Vendor Service Fee POLI Type',
                UNITY_Value__c = 'Vendor Services'
            );
            
            UNITY_General_Settings__c setting3 = new UNITY_General_Settings__c(
                Name = 'Service Fee Product Type',
                UNITY_Description__c = 'Vendor Service Fee Product Type',
                UNITY_Value__c = 'Vendor Service Fee'
            );
            
            UNITY_General_Settings__c setting4 = new UNITY_General_Settings__c(
                Name = 'Service Fee Product name',
                UNITY_Description__c = 'Vendor Service Fee Product Name',
                UNITY_Value__c = 'Vendor Service Fee'
            );
            
            UNITY_General_Settings__c setting5 = new UNITY_General_Settings__c(
                Name = 'PO_Invoiceable_Statuses',
                UNITY_Description__c = 'Comma separated list of statuses, when a PO should be invoiceable ',
                UNITY_Value__c = 'Final,Accepted'
            );
            
            generalSetting.add(setting1);
            generalSetting.add(setting2);
            generalSetting.add(setting3);
            generalSetting.add(setting4);
            generalSetting.add(setting5);
            insert generalSetting;
        }
        
        List<Account> accounts = UNITY_TestDataFactory.createAccounts(2, 'Krishna', Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
        List<Contact> contacts = UNITY_TestDataFactory.createContacts(2,accounts.get(0).Id);
        List<Case> cases = UNITY_TestDataFactory.createCases(2,accounts.get(0).Id,accounts.get(1).Id,contacts.get(0).Id,UNITY_Constants.CASE_SERVICE_REQUEST_RECORDTYPE);
        List<WorkOrder> workOrders = UNITY_TestDataFactory.createWorkOrders(2,cases.get(0).Id,accounts.get(0).id,UNITY_Constants.WO_SERVICE_REQUEST_RECORDTYPE);
        List<UNITY_Invoice__c> invoices = UNITY_TestDataFactory.createInvoices(2, cases.get(0).Id, accounts.get(0).Id);
        UNITY_Service_Contract__c serviceContract =new UNITY_Service_Contract__c();
        serviceContract.UNITY_Required_Documentation__c = 'Copy of Supplier Parts;Customer Required Sign Off';
        serviceContract.UNITY_Account__c = accounts.get(0).Id;
        insert serviceContract;
        WorkOrder wo =workOrders.get(0);
        wo.UNITY_Customer_Service_Contract__c =serviceContract.Id; 
        update wo;
        System.Test.startTest();
        
        //WorkOrder wo =[SELECT UNITY_Attachment_Compliant__c FROM WorkOrder WHERE id='a4O180000008YV0EAM' LIMIT 1];
        UNITY_Attachment__c attachment1 = new UNITY_Attachment__c();
        attachment1.Work_Order__c =wo.Id;
        attachment1.UNITY_Type__c ='Copy of Supplier Parts';
        insert attachment1;
        Order orderObj=new Order();
        orderObj.AccountId =  accounts.get(0).Id;
        orderObj.UNITY_Invoice__c=invoices.get(0).Id;
        orderObj.FSO__WorkOrder__c = wo.Id;
        orderObj.Status ='Draft';
        orderObj.EffectiveDate =System.today();
        insert orderObj;
        /*UNITY_Invoice__c invoiceObj = [SELECT id ,UNITY_Missing_Required_Documentation__c  FROM UNITY_Invoice__c where Id =:invoices.get(0).Id LIMIT 1];
    System.assertEquals(false,invoiceObj.UNITY_Missing_Required_Documentation__c);
    UNITY_Attachment__c attachment2 = new UNITY_Attachment__c();
    attachment2.Work_Order__c =wo.Id;
    attachment2.UNITY_Type__c ='Copy of Vendor Invoices';
    insert attachment2;
    update orderObj;
    UNITY_Invoice__c invoiceObj1 = [SELECT id ,UNITY_Missing_Required_Documentation__c  FROM UNITY_Invoice__c where Id =:invoices.get(0).Id LIMIT 1];
    System.assertEquals(false,invoiceObj.UNITY_Missing_Required_Documentation__c);*/
            //delete attachment1;
            /*delete orderObj;
    UNITY_Invoice__c invoiceObj2 = [SELECT id ,UNITY_Missing_Required_Documentation__c  FROM UNITY_Invoice__c where Id =:invoices.get(0).Id LIMIT 1];
    System.assertEquals(false,invoiceObj.UNITY_Missing_Required_Documentation__c);
    Order orderObj1=new Order();
    orderObj1.UNITY_Invoice__c=invoices.get(0).Id;
    orderObj1.FSO__WorkOrder__c = wo.Id;
    orderObj1.Status ='Draft';
    orderObj1.EffectiveDate =System.today();
    insert orderObj1;*/
        
        System.Test.stopTest();
    }
}