objects/UNITY_Proposal_Line_Item__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Product needs to have the Miner Record Type.</errorMessage>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Miner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Template_Config_Ext_ID__c</fullName>
        <label>Template Config Ext ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <description>The quote line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Labor - Installation</fullName>
                </value>
                <value>
                    <fullName>Labor - Service</fullName>
                </value>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Stock Receipt (Restocking)</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QTLI-{0000000000}</displayFormat>
        <label>Proposal Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Template_Configuration__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Applicable_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Define a template configuration for this child node. If provided, template would be recursively applied to this child object when created.</description>
        <label>Applicable Template</label>
        <referenceTo>UNITY_Template_Configuration__c</referenceTo>
        <relationshipLabel>Templates Configuration (Applicable Template)</relationshipLabel>
        <relationshipName>Templates_Configuration1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Node_Type__c</fullName>
        <label>Node Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Node_Value__c</fullName>
        <label>Node Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Part_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Templates Configuration</relationshipLabel>
        <relationshipName>Templates_Configuration</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Product_Activity_Type__c</fullName>
        <label>Product Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UNITY_Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Standard Labor</fullName>
                </value>
                <value>
                    <fullName>Overtime Labor</fullName>
                </value>
                <value>
                    <fullName>Holiday Labor</fullName>
                </value>
                <value>
                    <fullName>Double Time Labor</fullName>
                </value>
                <value>
                    <fullName>Preventive Maintenance</fullName>
                </value>
                <value>
                    <fullName>Parts - New Construction</fullName>
                </value>
                <value>
                    <fullName>Parts - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Field Supplies</fullName>
                </value>
                <value>
                    <fullName>Freight - New Construction</fullName>
                </value>
                <value>
                    <fullName>Freight - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Pass Through Labor</fullName>
                </value>
                <value>
                    <fullName>Pass Through Parts</fullName>
                </value>
                <value>
                    <fullName>Pass Through Freight</fullName>
                </value>
                <value>
                    <fullName>Pass Through Rentals</fullName>
                </value>
                <value>
                    <fullName>Pass Through Tax</fullName>
                </value>
                <value>
                    <fullName>Rental - Equipment</fullName>
                </value>
                <value>
                    <fullName>Rental - New Construction</fullName>
                </value>
                <value>
                    <fullName>Rental - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Sublabor - New Construction</fullName>
                </value>
                <value>
                    <fullName>Sublabor - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Asset Mgmt Fees</fullName>
                </value>
                <value>
                    <fullName>Destination Credit</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Warranty</fullName>
                </value>
                <value>
                    <fullName>Double Time Travel</fullName>
                </value>
                <value>
                    <fullName>Holiday Travel</fullName>
                </value>
                <value>
                    <fullName>Overtime Travel</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Preventative Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Technician</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
                <value>
                    <fullName>Labor - Installation</fullName>
                </value>
                <value>
                    <fullName>Labor - Service</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Stock Receipt (Restocking)</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Non Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Target_Object_Record_Type__c</fullName>
        <label>Target Object Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UNITY_Target_Object__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ccccc</fullName>
                </value>
                <value>
                    <fullName>Preventative Maintenance</fullName>
                </value>
                <value>
                    <fullName>Project Management</fullName>
                </value>
                <value>
                    <fullName>Project Phase</fullName>
                </value>
                <value>
                    <fullName>Service Request</fullName>
                </value>
                <value>
                    <fullName>Site Survey</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
                <value>
                    <fullName>Usage Request</fullName>
                </value>
                <value>
                    <fullName>Customer Proposal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Target_Object__c</fullName>
        <label>Target Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>WorkOrder</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>OrderItem</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>UNITY_Proposal_Line_Item__c</fullName>
                </value>
                <value>
                    <fullName>UNITY_Proposal__c</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Template_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template Parent</label>
        <referenceTo>UNITY_Template_Configuration__c</referenceTo>
        <relationshipLabel>Templates Configuration</relationshipLabel>
        <relationshipName>Templates_Configuration</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Template Configuration</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates Configuration</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Template_Configuration_Line_Item__c.object
<CustomObject>
    <description>Template Configuration Child Object to hold &apos;Key&apos; &apos;Value&apos; pairs of any field of the Target Object and it&apos;s value.</description>
    <fields>
        <fullName>UNITY_Parent_Template_Configuration__c</fullName>
        <label>Parent Template Configuration</label>
        <referenceTo>UNITY_Template_Configuration__c</referenceTo>
        <relationshipLabel>Template Configuration Line Items</relationshipLabel>
        <relationshipName>UNITY_Template_Configuration_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Target_Object_Field_Value__c</fullName>
        <label>Target Object Field Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Target_Object_Field__c</fullName>
        <label>Target Object Field</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Template Configuration Line Item</label>
    <nameField>
        <displayFormat>TCLI-{00000}</displayFormat>
        <label>Template Configuration Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Template Configuration Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_TemplateConfigRelationshipLookups__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to help identify lookup fields for various objects to dynamically create relationships while creating the objects via Template Configuration</description>
    <fields>
        <fullName>UNITY_Child_Object__c</fullName>
        <description>Child Object</description>
        <label>UNITY_Child Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Parent_Lookup_Field__c</fullName>
        <description>Field Api name that identify the lookup to the parent</description>
        <label>UNITY_Parent Lookup Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Parent_Object__c</fullName>
        <description>Parent Object</description>
        <label>UNITY_Parent Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>UNITY_TemplateConfigRelationshipLookups</label>
</CustomObject>

classes/UNITY_MultiLevelHierarchyUtility.cls
public with sharing class UNITY_MultiLevelHierarchyUtility {

    public static Map<String,String> relationshipLookupsMap = new Map<String,String>();
    public static Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();  
    public static String TEMPLATE_CONFIG_EXT_ID_FIELDNAME = 'UNITY_Template_Config_Ext_ID__c';
    
    // used just for pricebook
    
    // Map<recordId, PriceBookId> 
    public static Map<Id, Id> priceBookMap {get;set;}
    // Map<PriceBookId+ProductId. PriceBookEntryId>
    public static Map<String, PricebookEntry> priceBookEntryMap {get;set;}
    public static Id standardPriceBookId {get;set;}
    
    static {
        Map<String, UNITY_TemplateConfigRelationshipLookups__c> relationshipLookupsCS = UNITY_TemplateConfigRelationshipLookups__c.getAll();
        for (UNITY_TemplateConfigRelationshipLookups__c relationshipLookup: relationshipLookupsCS.values()){
            String relationship = relationshipLookup.UNITY_Child_Object__c + '->' + relationshipLookup.UNITY_Parent_Object__c;
            String lookupField = relationshipLookup.UNITY_Parent_Lookup_Field__c;
            relationshipLookupsMap.put(relationship,lookupField);
        } 
        standardPriceBookId = UNITY_Constants.getStandardPriceBookId();
        
    }

    public static Map<Id,HierarchyNode> getHierarchies(List<UNITY_Template_Configuration__c> topLevelTemplateConfigs) {
        Map<Id,HierarchyNode> nodes = new Map<Id,HierarchyNode>();
        Set<Id> parentTemplateConfigIds = new Set<Id>();
     
        for (UNITY_Template_Configuration__c templateConfig : topLevelTemplateConfigs) {
            nodes.put(templateConfig.Id, new HierarchyNode(templateConfig));
            parentTemplateConfigIds.add(templateConfig.Id);
        }
     
        while (parentTemplateConfigIds.size() > 0) {
            Map<Id,UNITY_Template_Configuration__c> subordinateTemplateConfigs =
                new Map<Id,UNITY_Template_Configuration__c>([
                    SELECT Id, UNITY_Template_Parent__c , Name, UNITY_Applicable_Template__c, UNITY_Product_Type__c, UNITY_Product_Activity_Type__c, UNITY_Node_Type__c, UNITY_Node_Value__c, UNITY_Part_Lookup__c, UNITY_Target_Object__c, UNITY_Target_Object_Record_Type__c
                    FROM UNITY_Template_Configuration__c
                    WHERE UNITY_Template_Parent__c IN :parentTemplateConfigIds
                ]);
     
            parentTemplateConfigIds = subordinateTemplateConfigs.keySet();
     
            for (UNITY_Template_Configuration__c templateConfig : subordinateTemplateConfigs.values()) {
                HierarchyNode new_node = new HierarchyNode(templateConfig);
                nodes.put(templateConfig.id, new_node);
                HierarchyNode ref_node = nodes.get(templateConfig.UNITY_Template_Parent__c);
                ref_node.children.add(new_node);
            }
        }
        return nodes;
    }

    //Utility method for debugging. DO NOT USE!
    public static void printAllChildrenNames(List<UNITY_Template_Configuration__c> topLevelTemplateConfigs, Map<Id,HierarchyNode> nodes) {
        for (UNITY_Template_Configuration__c templateConfig : topLevelTemplateConfigs) {
            HierarchyNode ref_node = nodes.get(templateConfig.id);
            Set<Id> child_templateConfig_ids = traverseChildren(ref_node.children, nodes);
            List<String> names = new List<String>();
     
            for (Id ref_id : child_templateConfig_ids) {
                names.add(nodes.get(ref_id).node.name);
            }
            System.debug('ALL CHILDREN = ' + String.join(names, ', '));
        }
    }

    public static sObject[] createRelatedSObjects(Map<Id,HierarchyNode> nodes, String parentObjectType, Id parentId){
        sObject[] sObjectsToBeCreated = new List<sObject>();
        
        for (HierarchyNode currentNode : nodes.values()){
            sObjectsToBeCreated = traverseChildren(currentNode,parentObjectType, parentId, null);                   
        }
        
        return sObjectsToBeCreated;
    }
    
    public static sObject[] traverseChildren(HierarchyNode currentNode, String parentObjectType, Id parentId, sObject referenceObject){
        sObject[] newObjects = new List<sObject>();

        UNITY_Template_Configuration__c tempConfig = currentNode.node;
        List<UNITY_Template_Configuration_Line_Item__c> TCLIs = tempConfig.UNITY_Template_Configuration_Line_Items__r;
        
        String applicableTemplate =  tempConfig.UNITY_Applicable_Template__c;
        String nodeType = tempConfig.UNITY_Node_Type__c;
        String nodeValue = tempConfig.UNITY_Node_Value__c;
        String productType = tempConfig.UNITY_Product_Type__c;
        String productActivityType = tempConfig.UNITY_Product_Activity_Type__c;
        Id partLookup = tempConfig.UNITY_Part_Lookup__c;
        String targetObjectName = tempConfig.UNITY_Target_Object__c;
        String targetObjectRecordType = tempConfig.UNITY_Target_Object_Record_Type__c;
        Schema.SObjectType targetObjectType = gd.get(targetObjectName);
        sObject targetObject = targetObjectType.newSObject();
        String parentLookupField = relationshipLookupsMap.get(targetObjectName+'->'+parentObjectType);
        
        System.debug('#parentObjectType '+parentObjectType);
        System.debug('#targetObjectName '+targetObjectName);
        System.debug('#parentLookupField '+parentLookupField);
        if (parentId!=null){
            targetObject.put(parentLookupField, parentId);
        }else{
            Schema.SObjectField oField= targetObjectType.getDescribe().fields.getMap().get(parentLookupField);
            Schema.DescribeFieldResult dfr = oField.getDescribe();
            targetObject.putSObject(dfr.getRelationshipName(), referenceObject);
        } 
        if (TCLIs.size()>0){
            for (UNITY_Template_Configuration_Line_Item__c TCLI : TCLIs){
                Schema.sObjectType objectDef = gd.get(targetObjectName).getDescribe().getSObjectType();
                Map<String, Schema.SobjectField> ObjectFieldsMap = objectDef.getDescribe().fields.getMap();
                String fieldType = ObjectFieldsMap.get(TCLI.UNITY_Target_Object_Field__c).getDescribe().getType().name().ToLowerCase();
                System.debug('#fieldType '+fieldType);
                    
                if(fieldType == 'currency' || fieldType == 'double' || fieldType == 'percent' || fieldType == 'decimal' )
                {
                    targetObject.put(TCLI.UNITY_Target_Object_Field__c, decimal.valueOf(TCLI.UNITY_Target_Object_Field_Value__c.trim())); 
                }
                else if(fieldType == 'boolean')
                {
                    targetObject.put(TCLI.UNITY_Target_Object_Field__c, Boolean.valueOf(TCLI.UNITY_Target_Object_Field_Value__c)); 
                }                   
                else if(fieldType == 'date')
                {
                    targetObject.put(TCLI.UNITY_Target_Object_Field__c, date.valueOf(TCLI.UNITY_Target_Object_Field_Value__c)); 
                }                
                else
                {
                    targetObject.put(TCLI.UNITY_Target_Object_Field__c, TCLI.UNITY_Target_Object_Field_Value__c);
                }
            }
        }
        if (targetObjectName=='WorkOrder'){
            targetObject.put('Subject','Test Work Order from Hierarchy');
        }
        else if (targetObjectName=='UNITY_Proposal_Line_Item__c'){
            targetObject.put('UNITY_Quantity__c',Decimal.valueof(nodeValue));
            targetObject.put('UNITY_Product__c',partLookup);
            targetObject.put('UNITY_Type__c', productType);
            targetObject.put('UNITY_Activity_Type__c', productActivityType);
        }
        else if (targetObjectName=='Order'){
            targetObject.put('Pricebook2Id',standardPriceBookId);
            targetObject.put('Status','Draft');
            targetObject.put('EffectiveDate', Date.today());
        }
        else if (targetObjectName=='OrderItem'){
            targetObject.put('Quantity',Decimal.valueof(nodeValue));
            
            Id priceBookId = priceBookMap.get(parentId);
            if (priceBookId == null){
                priceBookId = standardPriceBookId;
            }
            Id productId = partLookup;
            
            System.debug('#priceBookEntryMap '+priceBookEntryMap);
            
            PricebookEntry pbE = priceBookEntryMap.get((string)priceBookId+(string)productId);
            targetObject.put('PricebookEntryId',pbE.Id);
            targetObject.put('UnitPrice',pbE.UnitPrice);
            targetObject.put('UNITY_Type__c', productType);
            targetObject.put('UNITY_Activity_Type__c', productActivityType);
        }
        else if (targetObjectName=='Asset'){
            targetObject.put('Product2Id',partLookup);
        }       
        newObjects.add(targetObject);   
        
        targetObject.put(TEMPLATE_CONFIG_EXT_ID_FIELDNAME,String.valueof(Datetime.now().getTime()));
        for (HierarchyNode childNode : currentNode.children) {
            sObject targetReferenceObject = targetObjectType.newSObject();
            //targetReferenceObject.put(TEMPLATE_CONFIG_EXT_ID_FIELDNAME,String.valueof(Datetime.now().getTime()));
            targetReferenceObject.put(TEMPLATE_CONFIG_EXT_ID_FIELDNAME,targetObject.get(TEMPLATE_CONFIG_EXT_ID_FIELDNAME));
            System.debug(newObjects);
            newObjects.addAll(traverseChildren(childNode,targetObjectName, null,targetReferenceObject));
        }
        return newObjects;
    }
     
    public static Set<Id> traverseChildren(List<HierarchyNode> children, Map<Id,HierarchyNode> nodes) {
        Set<Id> templateConfigIds = new Set<Id>();
        for (HierarchyNode ref_node : children) {
            templateConfigIds.add(ref_node.node.id);
            templateConfigIds.addAll(traverseChildren(ref_node.children, nodes));
        }
        return templateConfigIds;
    }


    // Add children nodes
    private static void addChildren(List<UNITY_Template_Configuration__c> templateConfigs, Map<Id,HierarchyNode> nodes, Set<Id> parentTemplateConfigIds) {
        for (UNITY_Template_Configuration__c templateConfig : templateConfigs) {
            HierarchyNode ref_node = nodes.get(templateConfig.UNITY_Template_Parent__c);
            HierarchyNode new_node = new HierarchyNode(templateConfig, ref_node);
            if (ref_node != null) {
                ref_node.children.add(new_node);
            }else{
                //nodes.put(templateConfig.id, new_node);
            }
            nodes.put(templateConfig.id, new_node);
            if (parentTemplateConfigIds != null) {
                parentTemplateConfigIds.add(templateConfig.id);
            }
        }
    }
     
    public static Map<Id,HierarchyNode> getHierarchiesOptimized(List<UNITY_Template_Configuration__c> topLevelTemplateConfigs) {
        Set<Id> parentTemplateConfigIds = new Set<Id>();
        Map<Id,HierarchyNode> nodes = new Map<Id,HierarchyNode>();
        for (UNITY_Template_Configuration__c templateConfig : topLevelTemplateConfigs) {
            nodes.put(templateConfig.Id, new HierarchyNode(templateConfig));
            parentTemplateConfigIds.add(templateConfig.Id);
        }
        return getHierarchiesOptimized(parentTemplateConfigIds, nodes);
    }
 
    // Queries 3 Levels (not including the top level) at a time, doesn't return the top level node in the map.
    public static Map<Id,HierarchyNode> getHierarchiesOptimized(Set<Id> topTemplateConfigIds) {
        
        Map<Id,HierarchyNode> result;
        
        Map<Id,HierarchyNode> nodes = new Map<Id,HierarchyNode>();
        Set<Id> parentTemplateConfigIds = topTemplateConfigIds;
     
        while (parentTemplateConfigIds.size() > 0) {
            Map<Id,UNITY_Template_Configuration__c> subordinateTemplateConfigs =
            new Map<Id,UNITY_Template_Configuration__c>([
                SELECT Id, Name, UNITY_Applicable_Template__c, UNITY_Product_Type__c, UNITY_Product_Activity_Type__c, UNITY_Node_Type__c, UNITY_Node_Value__c, UNITY_Part_Lookup__c, UNITY_Target_Object__c, UNITY_Target_Object_Record_Type__c,
                       UNITY_Template_Parent__c,
                       UNITY_Template_Parent__r.UNITY_Template_Parent__c,
                       UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c,
                       (Select Id, UNITY_Target_Object_Field__c, UNITY_Target_Object_Field_Value__c from UNITY_Template_Configuration_Line_Items__r)
                FROM   UNITY_Template_Configuration__c
                WHERE (UNITY_Template_Parent__c IN :parentTemplateConfigIds) OR
                      (UNITY_Template_Parent__r.UNITY_Template_Parent__c IN :parentTemplateConfigIds) OR
                      (UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c IN :parentTemplateConfigIds)]);
     
            List<UNITY_Template_Configuration__c> level1TemplateConfigs = new List<UNITY_Template_Configuration__c>();
            List<UNITY_Template_Configuration__c> level2TemplateConfigs = new List<UNITY_Template_Configuration__c>();
            List<UNITY_Template_Configuration__c> level3TemplateConfigs = new List<UNITY_Template_Configuration__c>();
     
            // Split UNITY_Template_Configuration__cs in levels
            for (UNITY_Template_Configuration__c templateConfig : subordinateTemplateConfigs.values()) {
                if (templateConfig.UNITY_Template_Parent__c != null) {
                    if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__c)) {
                        level1TemplateConfigs.add(templateConfig);
                    }
                    else if (templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__c != null) {
                        if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__c)) {
                            level2TemplateConfigs.add(templateConfig);
                        }
                        else if (templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c != null) {
                            if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c)) {
                                level3TemplateConfigs.add(templateConfig);
                            }
                        }
                    }
                }
            }
     
            Set<Id> next_parentTemplateConfigIds = new Set<Id>();
     
            // Add children on all levels found, one level at a time
        
            addChildren(level1TemplateConfigs, nodes, null);
            
            if (result == null){
                result = nodes.clone();
            }
            
            System.debug('#nodes1 '+nodes);
            
            addChildren(level2TemplateConfigs, nodes, null);
            
            System.debug('#nodes2 '+nodes);
            addChildren(level3TemplateConfigs, nodes, next_parentTemplateConfigIds);
            
            System.debug('#nodes3 '+nodes);
               
            // Use lowest level of UNITY_Template_Configuration__c ids for next SOQL query
            parentTemplateConfigIds = next_parentTemplateConfigIds;
        }
        return nodes;
    }


    // Queries 3 Levels (not including the top level) at a time, returns top level node as well.
    public static Map<Id,HierarchyNode> getHierarchiesOptimized(Set<Id> topTemplateConfigIds, Map<Id,HierarchyNode> nodes) {
        Set<Id> parentTemplateConfigIds = topTemplateConfigIds;
     
        while (parentTemplateConfigIds.size() > 0) {
            Map<Id,UNITY_Template_Configuration__c> subordinateTemplateConfigs =
            new Map<Id,UNITY_Template_Configuration__c>([
                SELECT Id, Name, UNITY_Applicable_Template__c, UNITY_Product_Type__c, UNITY_Product_Activity_Type__c, UNITY_Node_Type__c, UNITY_Node_Value__c, UNITY_Part_Lookup__c, UNITY_Target_Object__c, UNITY_Target_Object_Record_Type__c,
                       UNITY_Template_Parent__c,
                       UNITY_Template_Parent__r.UNITY_Template_Parent__c,
                       UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c
                FROM   UNITY_Template_Configuration__c
                WHERE (UNITY_Template_Parent__c IN :parentTemplateConfigIds) OR
                      (UNITY_Template_Parent__r.UNITY_Template_Parent__c IN :parentTemplateConfigIds) OR
                      (UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c IN :parentTemplateConfigIds)]);
     
            List<UNITY_Template_Configuration__c> level1TemplateConfigs = new List<UNITY_Template_Configuration__c>();
            List<UNITY_Template_Configuration__c> level2TemplateConfigs = new List<UNITY_Template_Configuration__c>();
            List<UNITY_Template_Configuration__c> level3TemplateConfigs = new List<UNITY_Template_Configuration__c>();
     
            // Split UNITY_Template_Configuration__cs in levels
            for (UNITY_Template_Configuration__c templateConfig : subordinateTemplateConfigs.values()) {
                if (templateConfig.UNITY_Template_Parent__c != null) {
                    if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__c)) {
                        level1TemplateConfigs.add(templateConfig);
                    }
                    else if (templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__c != null) {
                        if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__c)) {
                            level2TemplateConfigs.add(templateConfig);
                        }
                        else if (templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c != null) {
                            if (parentTemplateConfigIds.contains(templateConfig.UNITY_Template_Parent__r.UNITY_Template_Parent__r.UNITY_Template_Parent__c)) {
                                level3TemplateConfigs.add(templateConfig);
                            }
                        }
                    }
                }
            }
     
            Set<Id> next_parentTemplateConfigIds = new Set<Id>();
     
            // Add children on all levels found, one level at a time
        
            addChildren(level1TemplateConfigs, nodes, null);
            addChildren(level2TemplateConfigs, nodes, null);
            addChildren(level3TemplateConfigs, nodes, next_parentTemplateConfigIds);

            // Use lowest level of UNITY_Template_Configuration__c ids for next SOQL query
            parentTemplateConfigIds = next_parentTemplateConfigIds;
        }
        return nodes;
    }

    // Class that is used as nodes in the UNITY_Template_Configuration__c hierarchy tree built by this class
    public class HierarchyNode {
        public HierarchyNode parent;
        public UNITY_Template_Configuration__c node;
        public List<HierarchyNode> children;
     
        HierarchyNode(UNITY_Template_Configuration__c templateConfig, HierarchyNode parent) {
            this.parent = parent;
            this.node = templateConfig;
            this.children = new List<HierarchyNode>();
        }
     
        HierarchyNode(UNITY_Template_Configuration__c templateConfig) {
            this.parent = null;
            this.node = templateConfig;
            this.children = new List<HierarchyNode>();
        }
    }
}