objects/UNITY_Attachment__c.object
<CustomObject>
    <description>UNITY Attachment object</description>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Check Request Form</fullName>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>Miner Sign Off Sheet</fullName>
                </value>
                <value>
                    <fullName>Note To Biller</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty Information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>Atch-{0000000000}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_AuraAttachmentListController.cls
public class UNITY_AuraAttachmentListController {

    @AuraEnabled
    public static UNITYAttachmentWrapper getAttachmentWrapper(Id recordId) {
        UNITYAttachmentWrapper attachmentWrapper = new UNITYAttachmentWrapper();
        attachmentWrapper.attachmentList = new List<UNITY_Attachment__c>();
        attachmentWrapper.isCase = false;
        
        system.debug('@@@getAttachments recordId:'+recordId);

        if (isCaseObject(recordId))       {
        	attachmentWrapper.attachmentList = [Select Id, Name, UNITY_Type__c, Work_Order__r.WorkOrderNumber, Work_Order__r.Id,CreatedDate, CreatedById From UNITY_Attachment__c WHERE Work_Order__r.CaseId = :recordId];
			attachmentWrapper.isCase = true;            
        }
        else 
            attachmentWrapper.attachmentList= [Select Id, Name, UNITY_Type__c, Work_Order__r.WorkOrderNumber, Work_Order__r.Id, CreatedDate, CreatedById From UNITY_Attachment__c WHERE Work_Order__c = :recordId];
        
        system.debug('@@@getAttachments attachmentWrapper:'+attachmentWrapper);
        return attachmentWrapper;
    }
    
    private static boolean isCaseObject(Id recordId){
		//determine if this a Case or WO Id
        Map<String,String> keys = new Map<String,String>();
        Map<String,Schema.SobjectType> describe = Schema.getGlobalDescribe();
        for(String s:describe.keyset())
        	keys.put(describe.get(s).getDescribe().getKeyPrefix(),s);
        
		if (keys.get(String.valueOf(recordId).substring(0,3)) == 'Case')
            return true;
        else
            return false;
    }
    
    public class UNITYAttachmentWrapper
    {
        @AuraEnabled
        public List<UNITY_Attachment__c> attachmentList {get;set;}
        @AuraEnabled
        public Boolean isCase {get;set;}
    }
}