objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Craft</fullName>
                </value>
                <value>
                    <fullName>MNS</fullName>
                </value>
                <value>
                    <fullName>MSP Atlanta</fullName>
                </value>
                <value>
                    <fullName>MSP Conroe (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP El Paso</fullName>
                </value>
                <value>
                    <fullName>MSP Houston</fullName>
                </value>
                <value>
                    <fullName>MSP Houston (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Jacksonville</fullName>
                </value>
                <value>
                    <fullName>MSP Memphis</fullName>
                </value>
                <value>
                    <fullName>MSP Miami</fullName>
                </value>
                <value>
                    <fullName>MSP Nashville</fullName>
                </value>
                <value>
                    <fullName>MSP New Orleans</fullName>
                </value>
                <value>
                    <fullName>MSP Orlando</fullName>
                </value>
                <value>
                    <fullName>MSP Phoenix</fullName>
                </value>
                <value>
                    <fullName>MSP San Antonio</fullName>
                </value>
                <value>
                    <fullName>MSP Tampa</fullName>
                </value>
                <value>
                    <fullName>NSBS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Default_Labor_Rate__c</fullName>
        <label>Default Labor Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract_Line_Item__c.object
<CustomObject>
    <description>Unity project, service contract line items will capture labor and part pricing related to a specific service contract for a vendor or customer.</description>
    <fields>
        <fullName>UNITY_Labor_Cost__c</fullName>
        <description>Labor Rate</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract__c</fullName>
        <description>Unity project, master detail relationship between Service Contract and its line items</description>
        <label>Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>UNITY_Service_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Trade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>Service_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Contract Line Item</label>
    <nameField>
        <displayFormat>SCL-{0000}</displayFormat>
        <label>Service Contract Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_UpdateWOContractedRate.cls
public class UNITY_UpdateWOContractedRate  implements Database.Batchable<SObject> {
    
    public Database.QueryLocator start(Database.BatchableContext context) {
         return Database.getQueryLocator([
              SELECT Id, UNITY_Vendor_Contract__r.Id, UNITY_Contracted_Rate__c, UNITY_Trade__c
                          FROM WorkOrder
                         WHERE UNITY_Contracted_Rate__c = null
                         AND Status != 'Canceled'
                         AND UNITY_Vendor_Contract__c != null
                         AND UNITY_Trade__c != null
                         AND RecordTypeId = '012310000011urpAAA'
             			 AND UNITY_Business_Unit__c in ('MNS','NSBS')
             			 AND CreatedDate >= 2017-07-01T00:00:00Z
             ]);
    }
    
    public void execute(Database.BatchableContext context, List<WorkOrder> scope) {
        Map<Id, Id> woContractMap = new Map<Id, Id>();
        for (WorkOrder wo: scope){
            woContractMap.put(wo.Id, wo.UNITY_Vendor_Contract__r.Id);
        }
        
        List<WorkOrder> woToUpdate = new List<WorkOrder>();
        Map<Id, UNITY_Service_Contract__c> vendorContractMap = new Map<Id,UNITY_Service_Contract__c> ([SELECT Id, UNITY_Default_Labor_Rate__c, Name, 
                                                                                                       (SELECT UNITY_Labor_Cost__c, UNITY_Trade__c,  UNITY_Trade__r.Name
                                                                                                        FROM UNITY_Service_Contract_Line_Items__r 
                                                                                                        WHERE RecordTypeId = :UNITY_Constants.SCLI_HOURLY_RATE_RECORDTYPE
                                                                                                       	ORDER BY LastModifiedDate desc
                                                                                                       )
                                                                                                       FROM UNITY_Service_Contract__c WHERE Id = :woContractMap.values()]);
        
        for (WorkOrder wo: scope){
            UNITY_Service_Contract__c vendorContract = vendorContractMap.get(wo.UNITY_Vendor_Contract__c);
            system.debug('@@@vendorContract'+vendorContract.Name);
            wo.UNITY_Contracted_Rate__c = vendorContract.UNITY_Default_Labor_Rate__c;
            if (vendorContract != null && vendorContract.UNITY_Service_Contract_Line_Items__r.size() > 0){
                system.debug('@@@unity trade:'+wo.UNITY_Trade__c);
                for (UNITY_Service_Contract_Line_Item__c scli: vendorContract.UNITY_Service_Contract_Line_Items__r){
                    system.debug('@@@applied rate scli'+scli);
                    if (wo.UNITY_Trade__c == scli.UNITY_Trade__c){
                        system.debug('@@@applied rate scli match'+scli);
                        wo.UNITY_Contracted_Rate__c = scli.UNITY_Labor_Cost__c;
                        break;
                    }
                }
            }
            woToUpdate.add(wo);
        }
        
        update woToUpdate;
			 
    }
    
     public void finish(Database.BatchableContext context) {
    }
 
}