objects/UNITY_Proposal__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds Agent Information working on the Case</description>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Business_Unit_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Business Unit Account)</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Case_Thread_ID__c</fullName>
        <formula>&quot;ref:_&quot;&amp;LEFT( $Organization.Id,5)&amp;SUBSTITUTE(RIGHT($Organization.Id,10),&quot;0&quot;,&quot;&quot;)&amp;&quot;._&quot;&amp;LEFT( UNITY_Case__r.Id ,5)&amp;SUBSTITUTE(LEFT(RIGHT(UNITY_Case__r.Id,10),5),&quot;0&quot;,&quot;&quot;)&amp;RIGHT(UNITY_Case__r.Id,5)&amp;&quot;:ref&quot;</formula>
        <label>Case Thread ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_PIN__c</fullName>
        <formula>UNITY_Work_Order__r.UNITY_Customer_PIN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer PIN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes (Customer)</relationshipLabel>
        <relationshipName>Quotes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Email_Logo_URL__c</fullName>
        <formula>UNITY_Case__r.UNITY_Email_Logo_URL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UNITY_Email_Logo_URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Shared_to_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shared to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price (without Adjustments or Tax)</label>
        <summarizedField>UNITY_Proposal_Line_Item__c.UNITY_Total_Price__c</summarizedField>
        <summaryForeignKey>UNITY_Proposal_Line_Item__c.UNITY_Proposal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UNITY_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UNITY_QuoteController.cls
/**
 * @programer: Rodrigo Birriel
 * @date:      03/06/2016
 */
public with sharing class UNITY_QuoteController {
    public UNITY_Proposal__c relatedTo {get; set;}
    public Id quoteID { get;
                        set {   
                                quoteID = value;
                                List<UNITY_Proposal__c> proposals = [SELECT Id,Name,UNITY_Agent__c,UNITY_Case_Thread_ID__c,CreatedDate,
                                                                            UNITY_Customer_PIN__c,UNITY_Email_Logo_URL__c,UNITY_Shared_to_Contact__c,
                                                                            UNITY_Work_Order__c,UNITY_Total_Price__c,RecordTypeId,
                                                                            UNITY_Work_Order__r.UNITY_Business_Unit_Account__r.Name,
                                                                            UNITY_Work_Order__r.workOrderNumber,UNITY_Business_Unit_Account__r.Website,
                                                                            UNITY_Work_Order__r.UNITY_Customer__c                                                     
                                                                     FROM UNITY_Proposal__c WHERE Id =: quoteID];
                                if(!proposals.isEmpty()) {
                                    relatedTo = proposals.get(0);
                                    List<User> users = [SELECT Id,TimeZoneSidKey FROM User WHERE Id =: relatedTo.UNITY_Agent__c];
                                    if(!users.isEmpty()){
                                        UNITY_Utils.DateTimeZone dtz = UNITY_Utils.getDateTime(relatedTo.CreatedDate,
                                                                                          'MMM d,  yyyy',
                                                                                          users.get(0).TimeZoneSidKey);
                                        CreatedDate= dtz.format;
                                    }   
                                    if(relatedTo.UNITY_Business_Unit_Account__r != null && relatedTo.UNITY_Business_Unit_Account__r.Website != null) {
                                        String site = relatedTo.UNITY_Business_Unit_Account__r.Website;
                                        beginSite = site.substringBefore('.');
                                        middleSite = site.substring(site.indexOf('.'), site.lastIndexOf('.')+1);
                                        endSite = site.substringAfterLast('.');
                                    }
                                }
                            }
    }
    
    public String CreatedDate{get;set;}
    
    public String beginSite {get; set;}
    public String middleSite {get; set;}
    public String endSite {get; set;}
}