objects/UNITY_CaseFromEmailFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is referenced in UNITY_CreateCaseFromEmail email handler class to map fields from email body to case fields for various templates.</description>
    <fields>
        <fullName>Additional_Description__c</fullName>
        <description>This text field can be used to specify any additional description regarding the field and it gets added in the Case.Description field.</description>
        <label>Additional Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>This field indicates the Salesforce field API name on Case object.</description>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Attribute__c</fullName>
        <description>This field specifies the search string within the incoming email body. This search string maps to some field on Case object within Salesforce.</description>
        <label>Search Attribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Key__c</fullName>
        <description>This field is used by the email handler class to match incoming email&apos;s &quot;from&quot; email address or email address domain. The &quot;from&quot; domain or address cannot be shared between different customers that use different templates.</description>
        <label>Template Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>This field specifies which customer this template is applicable to.</description>
        <label>Template Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>UNITY Case From Email Fields</label>
</CustomObject>

objects/UNITY_CaseFromEmailFieldValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is referenced in UNITY_CreateCaseFromEmail email handler class to map field values from email body to field values for Case fields for various templates.</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>This field specifies the Case field API name.</description>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Value__c</fullName>
        <description>This is the final value for the Case field that matches with the field definition within Salesforce.</description>
        <label>Final Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <description>This specifies the value parsed from the incoming email. This value will get mapped to the final value from Field_Value__c field and copied to the Case record.</description>
        <label>Source Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Key__c</fullName>
        <description>This field is used by the email handler class to match incoming email&apos;s &quot;from&quot; email address or email address domain. The &quot;from&quot; domain or address cannot be shared between different customers that use different templates. It has to match with UNITY_CaseFromEmailFields__c.Template_Key__c</description>
        <label>Template Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Name__c</fullName>
        <description>This field specifies which customer this template is applicable to.</description>
        <label>Template Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>UNITY Case From Email Field Values</label>
</CustomObject>

objects/UNITY_EmailDomainMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maps default field values on Case based on email domain or email address.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This field specifies what Business Unit on the Case is applicable to the case based on &quot;To&quot; email address domain for Email-to-Case</description>
        <label>Business Unit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <description>This field specifies what Case Origin is applicable to the case based on &quot;To&quot; email address domain for Email-to-Case</description>
        <label>Case Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Email_Domain__c</fullName>
        <description>Domain for the &quot;To&quot; email address</description>
        <label>To Email Domain</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>UNITY Email Domain Map</label>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_CreateCaseFromEmailTest.cls
@isTest
private class UNITY_CreateCaseFromEmailTest {

    static testMethod void TestCreateCaseFromTemplateEmail() {
        //create custom setting data
        List<UNITY_CaseFromEmailFields__c> fieldMap = new List<UNITY_CaseFromEmailFields__c>();
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'Priority', Additional_Description__c = 'This is a test',
                                                Search_Attribute__c = 'Priority', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'Priority-UNITY_CreateCaseFromEmail'));
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'UNITY_NTE_Threshold__c',
                                                Search_Attribute__c = 'Not to Exceed Amt', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'NTE-UNITY_CreateCaseFromEmail'));
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'UNITY_Service_Channel_Create_Date_Time__c',
                                                Search_Attribute__c = 'CreatedDate', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'CreatedDate-UNITY_CreateCaseFromEmail'));
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'UNITY_SL_Invoice_Date__c',
                                                Search_Attribute__c = 'Invoice Date', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'InvDate-UNITY_CreateCaseFromEmail'));
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'IsEscalated',
                                                Search_Attribute__c = 'IsEscalated', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'IsEscalated-UNITY_CreateCaseFromEmail'));
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                Field_Name__c = 'AccountId',
                                                Search_Attribute__c = 'Service Address', 
                                                Template_Key__c = 'someaddress@email.com',
                                                Name = 'Address-UNITY_CreateCaseFromEmail'));
        insert fieldMap;
        
        UNITY_CaseFromEmailFieldValues__c fieldValueMap = new UNITY_CaseFromEmailFieldValues__c(Template_Name__c = 'UnitTest-UNITY_CreateCaseFromEmail', 
                                                                                    Field_Name__c = 'Priority',
                                                                                    Source_Value__c = 'Emergency', 
                                                                                    Template_Key__c = 'someaddress@email.com',
                                                                                    Final_Value__c = '4 Hour Response',
                                                                                    Name = 'UnitTest-UNITY_CreateCaseFromEmail');
        insert fieldValueMap;
        
        Account testAccount = new Account(Name = 'Test Acc for UNITY_CreateCaseFromEmail', ShippingStreet = '123 Test Ln', ShippingCity = 'SF', ShippingState = 'CA', ShippingPostalCode = '94104',
                                            BillingStreet = '123 Test Ln', BillingCity = 'SF', BillingState = 'CA', BillingPostalCode = '94104');
        insert testAccount;
        
        UNITY_Service_Contract__c testContract = new UNITY_Service_Contract__c(UNITY_Account__c = testAccount.Id, UNITY_IS_Active__c = TRUE);
        insert testContract;
        
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        // setup the data for the email
        email.subject = 'UnitTest-UNITY_CreateCaseFromEmail';
        email.fromAddress = 'someaddress@email.com';
        email.toAddresses = new String[] {'toAddress@email.com'};
        email.plainTextBody = 'email body\nPriority: High\nNot to Exceed Amt: 200.00\nCreatedDate: ' + System.now() + 
                                '\nUNITY_SL_Invoice_Date__c: ' + Date.today() + '\nIsEscalated: false\nService Address: 123 Test Ln, SF, CA 94104';
        // add an Binary attachment
        Messaging.InboundEmail.BinaryAttachment binAttachment = new Messaging.InboundEmail.BinaryAttachment();
        binAttachment.body = blob.valueOf('my attachment binary');
        binAttachment.fileName = 'textfileone.txt';
        binAttachment.mimeTypeSubType = 'text/plain';
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { binAttachment };
        // add an Text atatchment
        Messaging.InboundEmail.TextAttachment txtAttachment = new Messaging.InboundEmail.TextAttachment();
        txtAttachment.body = 'my attachment text';
        txtAttachment.fileName = 'textfiletwo.txt';
        txtAttachment.mimeTypeSubType = 'text/plain';
        email.textAttachments = new Messaging.inboundEmail.TextAttachment[] { txtAttachment };
        // call the email service class and test it with the data in the testMethod
        UNITY_CreateCaseFromEmail testInbound = new UNITY_CreateCaseFromEmail();
        testInbound.handleInboundEmail(email, env);
    }
    
    static testMethod void TestCreateCaseFromGenericEmail() {
        //create custom setting data
        List<UNITY_CaseFromEmailFields__c> fieldMap = new List<UNITY_CaseFromEmailFields__c>();
        fieldMap.add(new UNITY_CaseFromEmailFields__c(Template_Name__c = 'Generic', 
                                                Field_Name__c = 'Origin',
                                                Search_Attribute__c = 'Origin',
                                                Template_Key__c = 'email.com',
                                                Name = 'Generic-UNITY_CreateCaseFromEmail'));
        
        insert fieldMap;
        
        List<UNITY_EmailDomainMap__c> domainMap = new List<UNITY_EmailDomainMap__c>();
        domainMap.add(new UNITY_EmailDomainMap__c(Business_Unit__c = 'MNS', Case_Origin__c = 'Email-MNS', To_Email_Domain__c = 'email.com', Name = 'TestCreateCaseFromGenericEmail'));
        insert domainMap;
        
        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        // setup the data for the email
        email.subject = 'UnitTest-UNITY_CreateCaseFromEmail';
        email.fromAddress = 'someaddress@email.com';
        email.toAddresses = new String[] {'toAddress@email.com'};
        email.plainTextBody = 'email body\nOrigin: Email\n';
        
        // call the email service class and test it with the data in the testMethod
        UNITY_CreateCaseFromEmail testInbound = new UNITY_CreateCaseFromEmail();
        testInbound.handleInboundEmail(email, env);
    }
}