objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_BU_MNS_SC_ID__c</fullName>
        <externalId>true</externalId>
        <label>BU MNS SC ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Craft</fullName>
                </value>
                <value>
                    <fullName>MNS</fullName>
                </value>
                <value>
                    <fullName>MSP Atlanta</fullName>
                </value>
                <value>
                    <fullName>MSP Conroe (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP El Paso</fullName>
                </value>
                <value>
                    <fullName>MSP Houston</fullName>
                </value>
                <value>
                    <fullName>MSP Houston (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Jacksonville</fullName>
                </value>
                <value>
                    <fullName>MSP Memphis</fullName>
                </value>
                <value>
                    <fullName>MSP Miami</fullName>
                </value>
                <value>
                    <fullName>MSP Nashville</fullName>
                </value>
                <value>
                    <fullName>MSP New Orleans</fullName>
                </value>
                <value>
                    <fullName>MSP Orlando</fullName>
                </value>
                <value>
                    <fullName>MSP Phoenix</fullName>
                </value>
                <value>
                    <fullName>MSP San Antonio</fullName>
                </value>
                <value>
                    <fullName>MSP Tampa</fullName>
                </value>
                <value>
                    <fullName>NSBS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Customer_IVR_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer IVR Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Miner_IVR_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Miner IVR Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITYPM_ServiceContractHandler.cls
public with sharing class UNITYPM_ServiceContractHandler extends UNITY_BaseHandler{
    

	public override void bulkBefore(List<SObject> newList_SC, List<SObject> oldList_SC, Map<Id,SObject> oldMap_SC, Map<Id,SObject> newMap_SC){
        system.debug('@@@UNITYPM_ServiceContractHandler');
        if (trigger.isInsert){
           Set<ID> accIDs = new Set <ID>();
            for (SObject obj: newList_SC){
              UNITY_Service_Contract__c srvCnt = (UNITY_Service_Contract__c)obj;
              
              srvCnt.UNITY_Miner_IVR_Required__c = true;
              srvCnt.UNITY_Customer_IVR_Required__c = true;
              
              if ( srvCnt.UNITY_IS_Active__c != false)
                   accIDs.add(srvCnt.UNITY_Account__c) ;
            }
            
          if ( accIDs.size() > 0) { 
            List<UNITY_Service_Contract__c> srvCntList =  [SELECT UNITY_Business_Unit__c , UNITY_Account__c, RecordType.Name, UNITY_IS_Active__c, UNITY_BU_MNS_SC_ID__c 
                    FROM UNITY_Service_Contract__c  
                         WHERE UNITY_Account__c IN :accIDs 
                            AND RecordType.Name = 'Preventative Maintenance' AND UNITY_IS_Active__c = true];
            if ( srvCntList.size() > 0){
               for (UNITY_Service_Contract__c srvCnt :srvCntList) {
                   string buMNS = srvCnt.UNITY_Account__c + srvCnt.RecordType.Name + srvCnt.UNITY_Business_Unit__c;
                   if ( buMNS == srvCnt.UNITY_BU_MNS_SC_ID__c ){
                    newList_SC[0].addError('You can not add a New Preventative Maintenance Service Contract. This Vendor Account contains this type of contract and it is Active.');
                   }
               }
            }
          }
        }
    }
}