objects/UNITY_Proposal__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Status__c</fullName>
        <label>Customer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Manager Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Total_Cost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>UNITY_Proposal_Line_Item__c.UNITY_Total_Cost__c</summarizedField>
        <summaryForeignKey>UNITY_Proposal_Line_Item__c.UNITY_Proposal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price (without Adjustments or Tax)</label>
        <summarizedField>UNITY_Proposal_Line_Item__c.UNITY_Total_Price__c</summarizedField>
        <summaryForeignKey>UNITY_Proposal_Line_Item__c.UNITY_Proposal__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UNITY_Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Proposal_Line_Item__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Product needs to have the Miner Record Type.</errorMessage>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Miner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Proposal__c</fullName>
        <label>Quote</label>
        <referenceTo>UNITY_Proposal__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Tax_Code__c</fullName>
        <description>The tax code applied to the quote line</description>
        <label>Tax Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Cost__c</fullName>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QTLI-{0000000000}</displayFormat>
        <label>Proposal Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_QuoteToOrderConverter.cls
global class UNITY_QuoteToOrderConverter{

    webservice static String convertQuote(Id quoteId){
        UNITY_Proposal__c quote = [SELECT Id, UNITY_Account__c,UNITY_Work_Order__c, UNITY_Work_Order__r.Pricebook2Id, UNITY_Status__c FROM UNITY_Proposal__c WHERE id =: quoteid];
        if(quote.UNITY_Status__c != 'Accepted'){
            return 'The quote has not been approved by the customer yet. Please wait for approval.';
        }
        
        List<UNITY_Proposal_Line_Item__c> quoteLineItems = [SELECT Id, UNITY_Tax_Code__c, UNITY_Price__c, UNITY_Product__c, UNITY_Total_Price__c,UNITY_Total_Cost__c, UNITY_Quantity__c FROM UNITY_Proposal_Line_Item__c WHERE UNITY_Proposal__c =: quoteid];

        Set<Id> produsctIdSet = new Set<Id>();
        for(UNITY_Proposal_Line_Item__c qli : quoteLineItems ){
            produsctIdSet.add(qli.UNITY_Product__c);
        }

        List<PriceBookEntry> priceBookEntries = [SELECT Id, IsActive, Pricebook2Id, Product2Id FROM PriceBookEntry WHERE IsActive = True AND Pricebook2Id =: quote.UNITY_Work_Order__r.Pricebook2Id AND Product2Id IN: produsctIdSet];
        Map<Id,Id> productToPriceBookEntryMap = new Map<Id,Id>();
        for(PriceBookEntry pbe : priceBookEntries ){
            productToPriceBookEntryMap.put(pbe.Product2Id, pbe.Id); 
        }
        
        Order o = new Order();
        o.AccountId = quote.UNITY_Account__c;
        o.FSO__WorkOrder__c = quote.UNITY_Work_Order__c;
        o.Status = 'Draft';
        o.EffectiveDate = Date.today();
        insert o;
        
        List<OrderItem> orderItems = new List<OrderItem>();
        for(UNITY_Proposal_Line_Item__c qli : quoteLineItems){
            OrderItem oi = new OrderItem();
            oi.UNITY_Total_Cost__c = qli.UNITY_Total_Cost__c;
            oi.UNITY_Total_Price__c = qli.UNITY_Total_Price__c;
            oi.Quantity = qli.UNITY_Quantity__c;
            oi.OrderId = o.Id;
            oi.UnitPrice = qli.UNITY_Price__c;
            oi.PricebookEntryId = productToPriceBookEntryMap.get(qli.UNITY_Product__c);
            oi.UNITY_Tax_Code__c = qli.UNITY_Tax_Code__c;
            orderItems.add(oi);
        }
        insert orderItems;
        return 'Purchase order have been created';
    }

}