objects/UNITY_CaseFromEmailFields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is referenced in UNITY_CreateCaseFromEmail email handler class to map fields from email body to case fields for various templates.</description>
    <fields>
        <fullName>Additional_Description__c</fullName>
        <description>This text field can be used to specify any additional description regarding the field and it gets added in the Case.Description field.</description>
        <label>Additional Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>This field indicates the Salesforce field API name on Case object.</description>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Search_Attribute__c</fullName>
        <description>This field specifies the search string within the incoming email body. This search string maps to some field on Case object within Salesforce.</description>
        <label>Search Attribute</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Delimiter__c</fullName>
        <description>Every record for each template had the same value. This is the delimiter text that separates search string (field) in an email template from the value. UNITY_CreateCaseFromEmail.cls searches this pattern in the email body using regex. Examples: If template has a string &quot;Priority : P4&quot; then this field should have value &quot;:&quot;
For line breaks use &quot;\n&quot;.</description>
        <label>Template Delimiter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Key__c</fullName>
        <description>This field is used by the email handler class to match incoming email&apos;s &quot;from&quot; email address or email address domain. The &quot;from&quot; domain or address cannot be shared between different customers that use different templates.</description>
        <label>Template Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>UNITY Case From Email Fields</label>
</CustomObject>

objects/UNITY_CaseFromEmailFieldValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is referenced in UNITY_CreateCaseFromEmail email handler class to map field values from email body to field values for Case fields for various templates.</description>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>This field specifies the Case field API name.</description>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Value__c</fullName>
        <description>This is the final value for the Case field that matches with the field definition within Salesforce.</description>
        <label>Final Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <description>This specifies the value parsed from the incoming email. This value will get mapped to the final value from Field_Value__c field and copied to the Case record.</description>
        <label>Source Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Key__c</fullName>
        <description>This field is used by the email handler class to match incoming email&apos;s &quot;from&quot; email address or email address domain. The &quot;from&quot; domain or address cannot be shared between different customers that use different templates. It has to match with UNITY_CaseFromEmailFields__c.Template_Key__c</description>
        <label>Template Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>UNITY Case From Email Field Values</label>
</CustomObject>

objects/UNITY_EmailDomainMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Maps default field values on Case based on email domain or email address.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This field specifies what Business Unit on the Case is applicable to the case based on &quot;To&quot; email address domain for Email-to-Case</description>
        <label>Business Unit</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <description>This field specifies what Case Origin is applicable to the case based on &quot;To&quot; email address domain for Email-to-Case</description>
        <label>Case Origin</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <description>Name of the Case Owner - Queue/User</description>
        <label>Owner Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Email_Domain__c</fullName>
        <description>Domain for the &quot;To&quot; email address</description>
        <label>To Email Domain</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>UNITY Email Domain Map</label>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Craft</fullName>
                </value>
                <value>
                    <fullName>MNS</fullName>
                </value>
                <value>
                    <fullName>MSP Atlanta</fullName>
                </value>
                <value>
                    <fullName>MSP Conroe (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP El Paso</fullName>
                </value>
                <value>
                    <fullName>MSP Houston</fullName>
                </value>
                <value>
                    <fullName>MSP Houston (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Jacksonville</fullName>
                </value>
                <value>
                    <fullName>MSP Memphis</fullName>
                </value>
                <value>
                    <fullName>MSP Miami</fullName>
                </value>
                <value>
                    <fullName>MSP Nashville</fullName>
                </value>
                <value>
                    <fullName>MSP New Orleans</fullName>
                </value>
                <value>
                    <fullName>MSP Orlando</fullName>
                </value>
                <value>
                    <fullName>MSP Phoenix</fullName>
                </value>
                <value>
                    <fullName>MSP San Antonio</fullName>
                </value>
                <value>
                    <fullName>MSP Tampa</fullName>
                </value>
                <value>
                    <fullName>NSBS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_EmailToCaseParser.cls
public class UNITY_EmailToCaseParser {

    public static Case parse(Messaging.inboundEmail email){

        Case newCase;

        String subject     = email.subject.trim();
        String fromAddress = email.fromAddress;
        String fromDomain  = fromAddress.split('@')[1];
        String toDomain    = email.toAddresses[0].split('@')[1];
        
        List<Attachment> attachments = new List<Attachment>();
        //Get any Text Attachment
        if (email.textAttachments != null) {
            for(Messaging.Inboundemail.TextAttachment tAttachment : email.textAttachments) {
                Attachment txtAttachment = new Attachment();
                txtAttachment.Name = tAttachment.fileName;
                txtAttachment.Body = Blob.valueOf(tAttachment.body);
                attachments.add(txtAttachment);
            }
        }
        
        //Get any Binary Attachment
        if (email.binaryAttachments != null) {
            for(Messaging.Inboundemail.BinaryAttachment bAttachment : email.binaryAttachments) {
                Attachment binAttachment = new Attachment();
                binAttachment.Name = bAttachment.fileName;
                binAttachment.Body = bAttachment.body;
                attachments.add(binAttachment);
            }
        }
        
        //Get default values based on "To" email address domain
        List<UNITY_EmailDomainMap__c> domainMaps = [SELECT Case_Origin__c, Business_Unit__c, Owner_Name__c FROM UNITY_EmailDomainMap__c WHERE To_Email_Domain__c = :toDomain];
        String bu = domainMaps.size() > 0 ? domainMaps[0].Business_Unit__c : null;
        String origin = domainMaps.size() > 0 ? domainMaps[0].Case_Origin__c : null;
        Id ownerId;
        if(domainMaps.size() > 0) {
            List<QueueSobject> caseOwner = [SELECT QueueId FROM QueueSobject WHERE Queue.Name = :domainMaps[0].Owner_Name__c AND SobjectType = 'Case'];
            ownerId = caseOwner.size() > 0 ? caseOwner[0].QueueId : null;
        }
        
        // Create a Case
        newCase = new Case(Subject = subject, SuppliedName = email.fromName, SuppliedEmail = email.fromAddress, UNITY_Business_Unit__c = bu, Origin = origin, OwnerId = ownerId);
        
        //CLAY: Debug for parsing
        System.debug('=====================CLAY: defining maps');
        System.debug('>>> Subject: ' + newCase.Subject);
        System.debug('>>> SuppliedName: '  + newCase.SuppliedName);
        System.debug('>>> SuppliedEmail: ' + newCase.SuppliedEmail);
        System.debug('>>> BU: '            + newCase.UNITY_Business_Unit__c);
        System.debug('>>> Origin: '        + newCase.Origin);
        System.debug('>>> OwnerId: '       + newCase.OwnerId);

        System.debug('>>> fromDomain: '    + fromDomain);


        Map<String, Schema.sObjectField> caseFieldsMap = Schema.SObjectType.Case.fields.getMap();
        
        // Populate default fields
        Map<String, UNITY_CaseFromEmailFields__c> fieldMappings = new Map<String, UNITY_CaseFromEmailFields__c>();
        Map<String, List<UNITY_CaseFromEmailFields__c>> emailFieldMatches = new Map<String, List<UNITY_CaseFromEmailFields__c>>();
        Map<String, String> searchWord_delimiter = new Map<String, String>();
        //CLAY: -The Generic template key is to cover for not finding any emailFieldMatches
        //To use this, you would have to have a setting for generic UNITY Case From Email Field custom setting.
        //Another way to solve this would be to utilize the TO email address for origin: lbrands@nsbs.net but failed parsing would create a 
        String templateKey = 'Generic';
        String delimiter   = ':';

        for (UNITY_CaseFromEmailFields__c def : [SELECT Additional_Description__c, Field_Name__c, Search_Attribute__c, 
                                            Template_Key__c, Template_Delimiter__c 
                                            FROM UNITY_CaseFromEmailFields__c 
                                            WHERE Template_Key__c like :'%'+fromDomain OR Template_Key__c = :templateKey]) {
            System.debug('>>> Case From Email Fields');
            System.debug('>>> Field_Name__c          -->'+def.Field_Name__c);
            System.debug('>>> Search_Attribute__c    -->'+def.Search_Attribute__c);
            System.debug('>>> Template_Delimiter__c  -->'+def.Template_Delimiter__c);
            searchWord_delimiter.put(def.Search_Attribute__c,def.Template_Delimiter__c);
            if(delimiter != def.Template_Delimiter__c && def.Template_Delimiter__c != null) delimiter = def.Template_Delimiter__c;
            if(emailFieldMatches.get(def.Template_Key__c) == null ) emailFieldMatches.put(def.Template_Key__c, new List<UNITY_CaseFromEmailFields__c>());
            
            emailFieldMatches.get(def.Template_Key__c).add(def);
            /*
            if(matches == null) {
               
                matches = new List<UNITY_CaseFromEmailFields__c>();
                emailFieldMatches.put(def.Template_Key__c, matches);
            }
            matches.add(def);*/
        }
        System.debug('>>> delimiter : ' + delimiter);
        System.debug('>>> emailFieldMatches :' + emailFieldMatches);
        
        //CLAY: Debug for parsing
        //System.debug('=====================CLAY:');
        //System.debug('==: emailFieldMatches:' + emailFieldMatches);
        
        // Extract the template name from the "from" email address/domain
        List<UNITY_CaseFromEmailFields__c> templates = new List<UNITY_CaseFromEmailFields__c>();
        if(emailFieldMatches.containsKey(fromDomain)) {
            templates = emailFieldMatches.get(fromDomain);
            templateKey = fromDomain;
        } else if(emailFieldMatches.containsKey(fromAddress)) {
            templates = emailFieldMatches.get(fromAddress);
            templateKey = fromAddress;
        } else {
            templates = emailFieldMatches.get('Generic');
        }
        
        for (UNITY_CaseFromEmailFields__c def : templates) {
            fieldMappings.put(def.Search_Attribute__c, def);
        }
        
        System.debug('>>> fieldMappings :' + fieldMappings);

        // Populate a map of source field values and their corresponding final values in Salesforce
        Map<String, Map<String, String>> fieldValuesMap = new Map<String, Map<String, String>>();

        for (UNITY_CaseFromEmailFieldValues__c values : [SELECT Field_Name__c, Source_Value__c, Final_Value__c 
                                                    FROM UNITY_CaseFromEmailFieldValues__c WHERE Template_Key__c = :templateKey]) {
            
            if(fieldValuesMap.get(values.Field_Name__c) == null) fieldValuesMap.put(values.Field_Name__c, new Map<String, String>());
            fieldValuesMap.get(values.Field_Name__c).put(values.Source_Value__c, values.Final_Value__c);
        }

        System.debug('>>> fieldValuesMap : '+fieldValuesMap);

        // Search "*: *\n" pattern in the email body using regex
        String emailBody = email.plainTextBody.replace('*','');

        emailBody = emailBody.replace(delimiter + '\n\n', delimiter + ' ');

        // Remove any text between '<'+ text +'>''
        emailBody = emailBody.replaceAll('<(.*?)>','');

        System.debug('>>> emailBody : '+emailBody);

        delimiter = ':';

        // Match anything 'key:value' (value can be AAAA:aaaaa)
        Matcher myMatcher = Pattern.compile('.*' + delimiter + '.*').matcher(emailBody);

        
        String       myMatch             = '';
        List<String> matchSet            = new List<String>();
        String       description         = '';
        Boolean      aux_found_key_value = false;
        

        while (myMatcher.find()) {

            myMatch = myMatcher.group(0);

            System.debug('>>> match : ' + myMatch);

            // pattern 'key '+': '+'Value'
            matchSet = myMatch.split(': ');

            aux_found_key_value = (matchSet.size() == 2);

            if(!aux_found_key_value)  continue;

            // Get the search literal or key
            string searchStr = matchSet[0].trim();
            System.debug('>>> searchStr : '   + searchStr);

            // Get the source value from email
            String sourceValue = matchSet[1].trim();
            System.debug('>>> sourceValue : ' + sourceValue);

            // Get the field name
            String fieldName = fieldMappings.get(searchStr) == null ? null : fieldMappings.get(searchStr).Field_Name__c;
            if(fieldName == null) continue;

            // Get Final field value from email Source value
            String fieldValue = sourceValue;
            if(fieldValuesMap.get(fieldName) != null) {
                Map<String, String> valuesMap = fieldValuesMap.get(fieldName);
                fieldValue = valuesMap.get(sourceValue) == null ? sourceValue : valuesMap.get(sourceValue);
            }
            
            // Get any additional one-off description text
            if(fieldMappings.get(searchStr) != null && fieldMappings.get(searchStr).Additional_Description__c != null) {
                description += fieldMappings.get(searchStr).Additional_Description__c + ': ' + fieldValue + '\n';
            }
            
            // Set the field value
            if(caseFieldsMap.get(fieldName) != null) {
                Schema.DescribeFieldResult F = caseFieldsMap.get(fieldName).getDescribe();
                string typename = F.getType().name().toLowerCase();
                
                // Convert to desired data type
                if(typename == 'reference') {
                    // Retrieve the lookup record based on fieldValue match
                    String sobjname = String.valueOf(F.getReferenceTo()).substringBetween('(',')'); 

                    if(sobjname == 'Account'){

                        String street, city, state, zip;
                        
                        String[] address = sourceValue.split(',');
                        street = address[0].trim();
                        city = address.size() > 1 ? address[1].trim() : null;
                        String [] stateZip = address.size() > 2 ? address[2].trim().split(' ') : null;
                        state = stateZip[0];
                        zip = stateZip.size() > 1 ? stateZip[1].trim() : null;
                       
                        String queryStr='select id from ' + sobjname ;
                        String queryStr_WHERE ='';
                        boolean allParameters = false;
                        if((street != null)&&(street != '')) {
                            queryStr_WHERE += 'ShippingStreet = \'' + street + '\'';

                            if((city != null)&&(city != '')) {
                                queryStr_WHERE += ' and ShippingCity = \'' + city + '\'';
                                allParameters  = true;/*
                                if((zip != null)&&(zip != '')) {
                                    queryStr_WHERE += ' and ShippingPostalCode = \'' + zip + '\'';
                                    allParameters  = true;
                                }*/
                            }
                        }
                        
                        /* State filter is not accurate because the data and email values mismatch based on state's full name or 2 char
                        if(state != null && state.length() > 2) {
                            queryStr += ' and ShippingState = \'' + state + '\'';
                        }*/
                        
                        
                        //CLAY: Debugging parser - need to see how we look for account:
                        System.debug('=======================CLAY: Querying for account:');
                        System.debug('Query String from email: ' + queryStr);
                        System.debug('Query String where part: ' + queryStr_WHERE);
                        if(allParameters){
                            List<sobject> objects = Database.query(queryStr+ ' where '+queryStr_WHERE);
                            System.debug('>>> Query : ' + objects);
                            if((!objects.isEmpty())&&(objects.size()==1)) {
                                newCase.put(fieldName, objects[0].Id);
                                if(fieldName == 'UNITY_Customer__c') {
                                    List<UNITY_Service_Contract__c> serviceContracts = [SELECT Id 
                                                                                        FROM   UNITY_Service_Contract__c 
                                                                                        WHERE  UNITY_Account__c = :objects[0].Id and UNITY_IS_Active__c = TRUE];
                                
                                    if(! serviceContracts.isEmpty()) {
                                        
                                        newCase.put('UNITY_Customer_Service_Contract__c', serviceContracts[0].Id);
                                    }
                                }
                            }
                        }
                    }
                    
                } else if (typename == 'percent' || typename == 'double') {
                    newCase.put(fieldName, Double.valueOf(fieldValue));
                } else if (typename == 'currency') {
                    if(fieldValue.contains('$')) {
                        fieldValue = fieldValue.replace( '$' , '' );
                    } else if(fieldValue.contains('USD')) {
                        fieldValue = fieldValue.replace( 'USD' , '' );
                    }
                    fieldValue = fieldValue.replace( ',' , '' );
                    newCase.put(fieldName, Double.valueOf(fieldValue));
                } else if (typename == 'integer') {
                    //fieldValue = fieldValue.replace( '$' , '' );
                    fieldValue = fieldValue.replace( ',' , '' );
                    newCase.put(fieldName, Integer.valueOf(fieldValue));
                }else if (typename == 'boolean') {
                    newCase.put(fieldName, Boolean.valueOf(fieldValue));
                }else if (typename == 'date') {
                    newCase.put(fieldName, Date.valueOf(fieldValue));
                } else if (typename == 'datetime') {
                    newCase.put(fieldName, DateTime.valueOf(fieldValue));
                } else {
                    newCase.put(fieldName, fieldValue);
                }
            }
        }
        
        newCase.Description = description + '\n' + email.plainTextBody;
        insert newCase;

        // Save attachments, if any
        if(! attachments.isEmpty()) {
            for(Attachment att : attachments) {
                att.ParentId = newCase.Id;
            }
            insert attachments;
        }

        return newCase;

    }

}