objects/UNITY_Invoice__c.object
<CustomObject>
    <description>UNITY Invoice object</description>
    <fields>
        <fullName>UNITY_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_Email__c</fullName>
        <description>Stores Customer email information from case</description>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Contract of Customer. Should be copied from the Case.</description>
        <label>UNITY_Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Customer)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Creation</fullName>
                    <default>true</default>
                    <label>Invoice Creation</label>
                </value>
                <value>
                    <fullName>Invoice sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Invoice Finalized</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Invoice Amended</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract_Margin_Value__c</fullName>
        <label>Service Contract Margin Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UNITY_Status__c</fullName>
        <label>Customer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price (Includes Service Charge)</label>
        <summarizedField>UNITY_Invoice_Line_Item__c.UNITY_Total_Price__c</summarizedField>
        <summaryFilterItems>
            <field>UNITY_Invoice_Line_Item__c.UNITY_Excluded_from_Total__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>UNITY_Invoice_Line_Item__c.UNITY_Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>UNITY_Invoice_Line_Item__c.UNITY_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Invoice_Line_Item__c.object
<CustomObject>
    <description>UNITY Invoice line items</description>
    <fields>
        <fullName>UNITY_Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Creation</fullName>
                </value>
                <value>
                    <fullName>Invoice sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Invoice Amended</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>UNITY_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Tax_Code__c</fullName>
        <description>The tax code applied to the invoice line</description>
        <label>Tax Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Craft</fullName>
                </value>
                <value>
                    <fullName>MNS</fullName>
                </value>
                <value>
                    <fullName>MSP Atlanta</fullName>
                </value>
                <value>
                    <fullName>MSP Conroe (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP El Paso</fullName>
                </value>
                <value>
                    <fullName>MSP Houston</fullName>
                </value>
                <value>
                    <fullName>MSP Houston (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Jacksonville</fullName>
                </value>
                <value>
                    <fullName>MSP Memphis</fullName>
                </value>
                <value>
                    <fullName>MSP Miami</fullName>
                </value>
                <value>
                    <fullName>MSP Nashville</fullName>
                </value>
                <value>
                    <fullName>MSP New Orleans</fullName>
                </value>
                <value>
                    <fullName>MSP Orlando</fullName>
                </value>
                <value>
                    <fullName>MSP Phoenix</fullName>
                </value>
                <value>
                    <fullName>MSP San Antonio</fullName>
                </value>
                <value>
                    <fullName>MSP Tampa</fullName>
                </value>
                <value>
                    <fullName>NSBS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Default_Labor_Rate__c</fullName>
        <label>Default Labor Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoicing_Increments__c</fullName>
        <inlineHelpText>Round to nearest X hour or bill to actual IVR.</inlineHelpText>
        <label>Invoicing Increments</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Next ¼ hr</fullName>
                </value>
                <value>
                    <fullName>Next ½ hr</fullName>
                </value>
                <value>
                    <fullName>Bill to IVR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Invoicing_Method__c</fullName>
        <label>Invoicing Method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Customer Web-Portal</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Flat File</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Service Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Margin__c</fullName>
        <label>Target Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UNITY_ServiceReport_Template__c</fullName>
        <label>Service Report Template</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Trip_Charge_Type__c</fullName>
        <label>Trip Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Hourly Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Trip_Charge__c</fullName>
        <label>Trip Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract_Line_Item__c.object
<CustomObject>
    <description>Unity project, service contract line items will capture labor and part pricing related to a specific service contract for a vendor or customer.</description>
    <fields>
        <fullName>UNITY_Labor_Cost__c</fullName>
        <description>Labor Rate</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract__c</fullName>
        <description>Unity project, master detail relationship between Service Contract and its line items</description>
        <label>Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>UNITY_Service_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Trade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>Service_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Trip_Charge_Type__c</fullName>
        <description>Type of Trip Charge By Trade</description>
        <label>Trip Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Hourly Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Trip_Charge__c</fullName>
        <description>Trip Charge by Trade</description>
        <label>Trip Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Contract Line Item</label>
    <nameField>
        <displayFormat>SCL-{0000}</displayFormat>
        <label>Service Contract Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_DisputeInvoiceButtonControllerTest.cls
@isTest
public class UNITY_DisputeInvoiceButtonControllerTest{
	//Setup Product and Pricebook Info
    public static Id PRICEBOOKENTRYID_T;
    public static Id PRICEBOOKENTRYID_L;
    public static Id PRICEBOOKENTRYID_P;
    public static Id PRODUCTID;
    static{
        //Create Product & pricebook
        Map<String,String> prodMapP = TestDataProvider.getProductAndPriceBookEntry(1,'Part');
        for(String s :prodMapP.keySet()){
            PRICEBOOKENTRYID_P = (Id)prodMapP.get(s);
            PRODUCTID = (Id)s;
        }
        Map<String,String> prodMapL = TestDataProvider.getProductAndPriceBookEntry(1,'Labor');
        for(String s :prodMapL.keySet()){
            PRICEBOOKENTRYID_L = (Id)prodMapL.get(s);
        }
        Map<String,String> prodMapT = TestDataProvider.getProductAndPriceBookEntry(1,'Travel');
        for(String s :prodMapT.keySet()){
            PRICEBOOKENTRYID_T = (Id)prodMapT.get(s);
        }
    }
    //Setup test data
    @testSetup
    public static void init(){
        TestDataProvider.unityTestSetup();
    }
   public static testMethod void runTest(){
            UNITY_Constants.MAX_TRIGGER_EXECUTION = 6;
        	//system.runAs(createUser()){
            
            Test.startTest();
            UNITY_Invoice__c invoice = prepareData();
			
            ApexPages.StandardController sc1 = new ApexPages.StandardController(invoice);
            UNITY_DisputeInvoiceButtonController controller = new UNITY_DisputeInvoiceButtonController(sc1);
            controller.disputeInvoice();
            
            List<UNITY_Invoice__c> invoices = [SELECT Id, UNITY_Invoice_Status__c FROM UNITY_Invoice__c];
            system.assertEquals(2, invoices.size());
            for(UNITY_Invoice__c i : invoices){
                if(i.Id == invoice.Id){
                    system.assertEquals('Disputed', i.UNITY_Invoice_Status__c);
                } 
            }
            
            List<UNITY_Invoice_Line_Item__c> oldilis = [SELECT Id FROM UNITY_Invoice_Line_Item__c WHERE UNITY_Invoice__c =: invoice.Id];
            //system.assertEquals(2, oldilis.size());
            List<UNITY_Invoice_Line_Item__c> newilis = [SELECT Id FROM UNITY_Invoice_Line_Item__c WHERE UNITY_Invoice__c !=: invoice.Id];
            //system.assertEquals(0, newilis .size());
            
            Order o1 = [SELECT Id, Status, UNITY_Updated_Invoice__c FROM Order];
            system.assertNotEquals(invoice.Id, o1.UNITY_Updated_Invoice__c);
            //system.assertNotEquals(null, o.UNITY_Updated_Invoice__c);
            //system.assertEquals('Invoice Regenerated', o.Status);
        	//} 

            Test.stopTest();
    }
    
    private static UNITY_Invoice__c prepareData(){
    
        //Get the accounts
        String custRTId = UNITY_Constants.ACCOUNT_CUSTOMER_RECORDTYPE;
        String vendRTId = UNITY_Constants.ACCOUNT_VENDOR_RECORDTYPE;
        String buRTId = UNITY_Constants.ACCOUNT_MINER_RECORDTYPE;
        String woRTId = UNITY_Constants.WO_SERVICE_REQUEST_RECORDTYPE;
        String usageRecRTId = UNITY_Constants.ORDER_USAGE_REQUEST_RECORDTYPE;
        String purchaseOrdRTId = UNITY_Constants.ORDER_PURCHASE_ORDER_RECORDTYPE;
        List<Account> accounts = [SELECT Id,RecordTypeId,Account_Email__c FROM Account];
        Account cust;
        Account vend;
        Account bu;
        for(Account a :accounts){
            if(a.RecordTypeId == custRTId)
                cust = a;
            if(a.RecordTypeId == vendRTId)
                vend = a;
            if(a.RecordTypeId == buRTId)
                bu = a;
        }
        Contact con = new Contact(FirstName = 'Test', LastName = 'Test', Email='test@test.com');
        insert con;
        
        Product2 product = new Product2(Name = 'Test');
        product.UNITY_Status__c = 'Inactive';
        insert product;
        
        Product2 product2 = new Product2(Name = 'Test2');
        product2.UNITY_Status__c = 'Inactive';
        insert product2;
        
        FSO__Skill__c skill = new FSO__Skill__c();
        skill.Name = 'Test Skill';
        
        insert skill;
        
        List<UNITY_Service_Contract__c> serviceContractList = new List<UNITY_Service_Contract__c>();
        
        List<UNITY_Service_Contract_Line_Item__c> serviceContractLineItemList = new List<UNITY_Service_Contract_Line_Item__c>();
        
        UNITY_Service_Contract__c serviceContract1 = new UNITY_Service_Contract__c();
        
        serviceContract1.UNITY_Account__c = cust.Id;
        serviceContract1.UNITY_Trip_Charge__c = 10;
        serviceContract1.UNITY_Trip_Charge_Type__c = 'Hourly Rate';
        serviceContract1.UNITY_Default_Labor_Rate__c = 75;
        serviceContract1.UNITY_Invoicing_Increments__c = 'Next ¼ hr';
        //serviceContract1.UNITY_Business_Unit__c = 'MNS;NSBS';
        serviceContract1.UNITY_IS_Active__c = true;
        serviceContract1.RecordTypeId = UNITY_Constants.SC_SERVICE_REQUEST_RECORDTYPE;
        serviceContract1.UNITY_ServiceReport_Template__c = 'my template';
        
        serviceContractList.add(serviceContract1);
        
        insert serviceContractList;
        
        UNITY_Service_Contract_Line_Item__c serviceContractLI1 = new UNITY_Service_Contract_Line_Item__c();
        
        serviceContractLI1.UNITY_Trade__c = skill.Id;
        serviceContractLI1.UNITY_Labor_Cost__c = 100;
        serviceContractLI1.UNITY_Service_Contract__c = serviceContract1.Id;
        serviceContractLI1.RecordTypeId = UNITY_Constants.SCLI_HOURLY_RATE_RECORDTYPE;
        
        serviceContractLineItemList.add(serviceContractLI1);
        
        insert serviceContractLineItemList;
        
        //Get the case
        Case c = [SELECT Id FROM Case LIMIT 1];
        c.UNITY_Customer_Service_Contract__c = serviceContract1.Id;
        update c;
        
        RecordType woRecordType = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'WorkOrder' AND DeveloperName = 'Service_Request'];  
        WorkOrder wo = new WorkOrder(RecordTypeId = woRecordType.Id, UNITY_Customer__c  = cust.Id ,UNITY_Assigned_Vendor__c = vend.Id, AccountId=cust.Id, CaseId = c.Id, Subject='Test');
        wo.UNITY_Customer_Service_Contract__c = serviceContract1.Id;
        insert wo;
        
        RecordType purchaseOrderRT = [SELECT Id FROM RecordType WHERE DeveloperName = 'UNITY_Purchase_Order' AND SobjectType ='Order'];
        
        UNITY_Service_Contract__c sc = new UNITY_Service_Contract__c(
            UNITY_Account__c = cust.Id, 
            UNITY_Margin__c = 10,
            UNITY_Invoicing_Method__c = 'Email'
        );
        insert sc;
        
        UNITY_Invoice__c invoice = new UNITY_Invoice__c(UNITY_Customer_Email__c = cust.Account_Email__c, UNITY_Case__c = c.Id, UNITY_Customer__c = cust.Id, UNITY_Customer_Service_Contract__c = sc.Id, UNITY_Service_Contract_Margin_Value__c = sc.UNITY_Margin__c);
        insert invoice;
        
        
        List<Order> orders = new List<Order>();
        Order o = new Order(RecordTypeId = purchaseOrderRT.id,UNITY_Invoice__c =invoice.id , FSO__WorkOrder__c = wo.Id, AccountId = cust.Id, EffectiveDate = Date.today(), Status = 'Draft');
        orders.add(o);
        
        insert orders;
        
        PricebookEntry pe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = product.Id, UnitPrice = 10, IsActive = true);
        insert pe;
        
        PricebookEntry pe2 = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = product2.Id, UnitPrice = 10, IsActive = true);
        insert pe2;
        
        List<OrderItem> orderItems = new List<OrderItem>();
        OrderItem oi = new OrderItem(OrderId = o.Id, PricebookEntryId = pe.Id, Quantity = 10, UnitPrice = 10, UNITY_Total_Price__c = 100, UNITY_Sales_Tax__c = 10, UNITY_Customer_Adjusted_Quantity__c = 1, UNITY_Tax_Code__c = 'Test', UNITY_Total_Cost__c = 7);
        orderItems.add(oi);
        
        OrderItem oi2 = new OrderItem(OrderId = o.Id, PricebookEntryId = pe2.Id, Quantity = 20, UnitPrice = 10, UNITY_Total_Price__c = 200, UNITY_Sales_Tax__c = 5, UNITY_Customer_Adjusted_Quantity__c = 2, UNITY_Tax_Code__c = 'Test2', UNITY_Total_Cost__c = 14);
        orderItems.add(oi2);
        
        insert orderItems;

        List<UNITY_Invoice_Line_Item__c> invoiceLinteItems = new List<UNITY_Invoice_Line_Item__c>();
        UNITY_Invoice_Line_Item__c ili1 = new UNITY_Invoice_Line_Item__c(UNITY_Invoice__c = invoice.Id, UNITY_Total_Price__c = 100, UNITY_Cost__c = 7, UNITY_Sales_Tax__c = 10, UNITY_PO_Price__c =10, UNITY_Quantity__c = 10, UNITY_Adjusted_Quantity__c = 1, Product__c = product.Id, UNITY_Tax_Code__c = 'Test');
        invoiceLinteItems.add(ili1);
        UNITY_Invoice_Line_Item__c ili2 = new UNITY_Invoice_Line_Item__c(UNITY_Invoice__c = invoice.Id, UNITY_Total_Price__c = 200, UNITY_Cost__c = 14, UNITY_Sales_Tax__c = 5, UNITY_PO_Price__c =10, UNITY_Quantity__c = 20, UNITY_Adjusted_Quantity__c = 2, Product__c = product2.Id, UNITY_Tax_Code__c = 'Test2');
        invoiceLinteItems.add(ili2);
        insert invoiceLinteItems;
        return invoice;
    }
    
    private static User createUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'testu', Email='testUser@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='unityTestUser@testorg.com');
        insert u;
        return u;
    }

}