objects/UNITY_Invoice__c.object
<CustomObject>
    <description>UNITY Invoice object</description>
    <fields>
        <fullName>UNITY_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Contract of Customer. Should be copied from the Case.</description>
        <label>UNITY_Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Customer)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoice_Comments__c</fullName>
        <label>Invoice Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Charge__c</fullName>
        <description>Service Charge Amount for Pass Through Customers</description>
        <label>Service Charge</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Status__c</fullName>
        <label>Customer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Invoice_Line_Item__c.object
<CustomObject>
    <description>UNITY Invoice line items</description>
    <fields>
        <fullName>UNITY_Excluded_from_Total__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Excluded from Total</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>UNITY_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Is_Vendor_Supply__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor Supply</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Craft</fullName>
                </value>
                <value>
                    <fullName>MNS</fullName>
                </value>
                <value>
                    <fullName>MSP Atlanta</fullName>
                </value>
                <value>
                    <fullName>MSP Conroe (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas</fullName>
                </value>
                <value>
                    <fullName>MSP Dallas (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP El Paso</fullName>
                </value>
                <value>
                    <fullName>MSP Houston</fullName>
                </value>
                <value>
                    <fullName>MSP Houston (CDC)</fullName>
                </value>
                <value>
                    <fullName>MSP Jacksonville</fullName>
                </value>
                <value>
                    <fullName>MSP Memphis</fullName>
                </value>
                <value>
                    <fullName>MSP Miami</fullName>
                </value>
                <value>
                    <fullName>MSP Nashville</fullName>
                </value>
                <value>
                    <fullName>MSP New Orleans</fullName>
                </value>
                <value>
                    <fullName>MSP Orlando</fullName>
                </value>
                <value>
                    <fullName>MSP Phoenix</fullName>
                </value>
                <value>
                    <fullName>MSP San Antonio</fullName>
                </value>
                <value>
                    <fullName>MSP Tampa</fullName>
                </value>
                <value>
                    <fullName>NSBS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Is_Pass_Through__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Pass Through</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Required_Documentation__c</fullName>
        <label>Required Documentation</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Check Request Form</fullName>
                </value>
                <value>
                    <fullName>Completed Survey</fullName>
                </value>
                <value>
                    <fullName>Copy of Supplier Parts</fullName>
                </value>
                <value>
                    <fullName>Credit Card Authorization</fullName>
                </value>
                <value>
                    <fullName>Customer Correspondence</fullName>
                </value>
                <value>
                    <fullName>Customer-Specific Service Report Sign-Off</fullName>
                </value>
                <value>
                    <fullName>Damage &amp; Abuse - Before &amp; After Pictures</fullName>
                </value>
                <value>
                    <fullName>Deposit Check</fullName>
                </value>
                <value>
                    <fullName>IVR Check in and Check out (Labor)</fullName>
                </value>
                <value>
                    <fullName>Lien Waiver</fullName>
                </value>
                <value>
                    <fullName>PM Checklist completed</fullName>
                </value>
                <value>
                    <fullName>PM Failures</fullName>
                </value>
                <value>
                    <fullName>Shipping Documents</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Estimate</fullName>
                </value>
                <value>
                    <fullName>Vendor&apos;s Invoice</fullName>
                </value>
                <value>
                    <fullName>Vendor Correspondence</fullName>
                </value>
                <value>
                    <fullName>W-9</fullName>
                </value>
                <value>
                    <fullName>Walmart - Ready to Invoice Still needs Paperwork</fullName>
                </value>
                <value>
                    <fullName>Warranty information</fullName>
                </value>
                <value>
                    <fullName>Work Acknowledgment Form (Service Sign-Off)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract_Line_Item__c.object
<CustomObject>
    <description>Unity project, service contract line items will capture labor and part pricing related to a specific service contract for a vendor or customer.</description>
    <fields>
        <fullName>UNITY_Service_Charge__c</fullName>
        <label>Service Charge</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract__c</fullName>
        <description>Unity project, master detail relationship between Service Contract and its line items</description>
        <label>Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>UNITY_Service_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Trade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>Service_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Contract Line Item</label>
    <nameField>
        <displayFormat>SCL-{0000}</displayFormat>
        <label>Service Contract Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_InvoiceTriggerHandlerUnitTest.cls
@isTest
public class UNITY_InvoiceTriggerHandlerUnitTest {

	@testSetup
	public static void data() {
		TestDataProvider.setKeyValueStore();
		Integer MAX_CUSTOMERS = 1;
		        Map<String,Object> caseFields                  = UNITY_TestDataFactory.MOCKUP_CASE_FIELDS;
                Map<String,Object> skillFields                 = UNITY_TestDataFactory.MOCKUP_FSO_SKILL_FIELDS;
                Map<String,Object> contactFields               = UNITY_TestDataFactory.MOCKUP_CONTACT_FIELDS;
                Map<String,Object> accountFields               = UNITY_TestDataFactory.MOCKUP_ACCOUNT_FIELDS;    
                Map<String,Object> productFields               = UNITY_TestDataFactory.MOCKUP_PRODUCT_FIELDS;
                Map<String,Object> workOrderFields             = UNITY_TestDataFactory.MOCKUP_WORK_ORDER_FIELDS;
                Map<String,Object> priceBookEntryFields        = UNITY_TestDataFactory.MOCKUP_PRICE_BOOK_ENTRY_FIELDS;
                Map<String,Object> serviceContractFields       = UNITY_TestDataFactory.MOCKUP_SERVICE_CONTRACT_FIELDS;
                Map<String,Object> serviceContractLineItemFields       = UNITY_TestDataFactory.MOCKUP_SERVICE_CONTRACT_LI_FIELDS;

                serviceContractFields.put('RecordTypeId'          , UNITY_Constants.SC_SERVICE_REQUEST_RECORDTYPE);
                serviceContractFields.put('UNITY_IS_Active__c'    , true);
                serviceContractFields.put('UNITY_Business_Unit__c', 'MNS');
                serviceContractFields.put('UNITY_Is_Pass_Through__c', true);
                serviceContractFields.put('UNITY_Required_Documentation__c', 'Customer-Specific Service Report Sign');

                caseFields.put('Type'                   , 'Customer');
                caseFields.put('RecordTypeId'           , UNITY_Constants.CASE_SERVICE_REQUEST_RECORDTYPE);
                caseFields.put('UNITY_Business_Unit__c' , 'MNS');

                accountFields.put('recordTypeId', UNITY_Constants.ACCOUNT_CUSTOMER_RECORDTYPE);
                accountFields.put('Type', 'Customer');
                accountFields.put('Name', 'C-'+UNITY_Utils.generateRandomPin());

                List<Account> customers = (List<Account>)UNITY_TestDataFactory.createObject(MAX_CUSTOMERS, Account.getSObjectType() , accountFields);
                insert customers;

                FSO__Skill__c onSkill = (FSO__Skill__c)UNITY_TestDataFactory.createObject(1, FSO__Skill__c.getSObjectType() , skillFields).get(0);
                insert onSkill;

        	List<Case>    					  cases    			= new List<Case>();
                List<Contact> 					  contacts 			= new List<Contact>();
                List<UNITY_Service_Contract__c>   serviceContracts    = new List<UNITY_Service_Contract__c>();
                Map<id,Map<String,SObject>> accountId_children  = new Map<id,Map<String,SObject>>();

                Case aux_case;
                Contact aux_contact;
                UNITY_Service_Contract__c aux_sc;
                for(Account customer :customers){

                	contactFields.put('AccountId', customer.id);
                	aux_contact =(Contact)UNITY_TestDataFactory.createObject(1, Contact.getSObjectType() , contactFields).get(0);
                	contacts.add(aux_contact);

                	caseFields.put('AccountId'        , customer.id);
        	        caseFields.put('UNITY_Customer__c', customer.id);
        	        caseFields.put('UNITY_Trade__c'   , onSkill.id);
        	        
        	        aux_case = (Case)UNITY_TestDataFactory.createObject(1, Case.getSObjectType() , caseFields).get(0);
        	        cases.add(aux_case);

        	        serviceContractFields.put('UNITY_Account__c', customer.id);
        	        aux_sc = (UNITY_Service_Contract__c)UNITY_TestDataFactory.createObject(1, UNITY_Service_Contract__c.getSObjectType() , serviceContractFields).get(0);
        	        serviceContracts.add(aux_sc);

        	        if(accountId_children.get(customer.id) == null) accountId_children.put(customer.id, new Map<String,SObject>());
        	        if(accountId_children.get(customer.id).get('cases') == null)            accountId_children.get(customer.id).put('cases', null);
        	        if(accountId_children.get(customer.id).get('contacts') == null)         accountId_children.get(customer.id).put('contacts', null);
        	        if(accountId_children.get(customer.id).get('serviceContract') == null) accountId_children.get(customer.id).put('serviceContract', null);
        	        
        	        accountId_children.get(customer.id).put('cases',aux_case);
        	        accountId_children.get(customer.id).put('contacts',aux_contact);
        	        accountId_children.get(customer.id).put('serviceContract',aux_sc);

                }
                insert contacts;
                insert serviceContracts;

                serviceContractLineItemFields.put('RecordTypeId', UNITY_Constants.SCLI_SERVICE_CHARGE_RECORDTYPE);
                serviceContractLineItemFields.put('UNITY_Trade__c', onSkill.id);
                List<UNITY_Service_Contract_Line_Item__c> scLineItems = new List<UNITY_Service_Contract_Line_Item__c>();

                for(Contact onContact :contacts){

                        accountId_children.get(onContact.AccountId).get('cases').put('ContactId',onContact.id);
                        //accountId_children.get(onContact.AccountId).get('cases').put('UNITY_Customer_Service_Contract__c',accountId_children.get(onContact.AccountId).get('serviceContract').get('Id'));
                	serviceContractLineItemFields.put('UNITY_Service_Contract__c', accountId_children.get(onContact.AccountId).get('serviceContract').get('Id'));
                        scLineItems.addAll((List<UNITY_Service_Contract_Line_Item__c>)UNITY_TestDataFactory.createObject(1, UNITY_Service_Contract_Line_Item__c.getSObjectType() , serviceContractLineItemFields));
                }
        
                insert cases;
                insert scLineItems;
        
        		// update the case with customer service contract
        		for(Case aCase : cases) {
                    aCase.UNITY_Customer_Service_Contract__c = serviceContracts.get(0).Id;
        		}

                productFields.put('UNITY_Product_Type__c', 'Customer Service Charge');
                productFields.put('UNITY_Status__c', 'Inactive');
                List<Product2> products = (List<Product2>)UNITY_TestDataFactory.createObject(1, Product2.getSObjectType() , productFields);
                insert products;
                
                priceBookEntryFields.put('IsActive', true);
                List<PricebookEntry> priceBookE = new List<PricebookEntry>();
                for(Product2 product :products){
                	priceBookEntryFields.put('Product2Id', product.id);
                	priceBookE.addAll((List<PricebookEntry>)UNITY_TestDataFactory.createObject(1, PricebookEntry.getSObjectType() , priceBookEntryFields));
                }
                insert priceBookE;

	}

	public static testMethod void codeCoverage() {
		
                
                Map<String,Object> invoiceFields   = UNITY_TestDataFactory.MOCKUP_INVOICE_FIELDS;
                Map<String,Object> invoiceLIFields = UNITY_TestDataFactory.MOCKUP_SERVICE_CONTRACT_LI_FIELDS;


                invoiceLIFields.put('UNITY_Is_Vendor_Supply__c',true); 
                invoiceLIFields.put('UNITY_Excluded_from_Total__c',false);

                invoiceFields.put('RecordTypeId',UNITY_Constants.INVOICE_VENDOR_RECORDTYPE);
                invoiceFields.put('UNITY_Service_Charge__c', 10);

                List<UNITY_Invoice__c>           invoices   = new List<UNITY_Invoice__c>();
                List<UNITY_Invoice__c>           aux_use_for_update_without_scli = new List<UNITY_Invoice__c>();
                List<UNITY_Invoice_Line_Item__c> invoicesLI = new List<UNITY_Invoice_Line_Item__c>();

                List<Case> cases = [SELECT id, UNITY_Customer__c,  UNITY_Customer_Service_Contract__c FROM Case];

                for(Case onCase :cases){
                        invoiceFields.put('UNITY_Case__c',onCase.id);
                        invoiceFields.put('UNITY_Customer__c',onCase.UNITY_Customer__c);
                        invoiceFields.put('UNITY_Customer_Service_Contract__c',onCase.UNITY_Customer_Service_Contract__c);
                        invoices.addall((List<UNITY_Invoice__c>)UNITY_TestDataFactory.createObject(1, UNITY_Invoice__c.getSObjectType() , invoiceFields));
                        aux_use_for_update_without_scli.addAll((List<UNITY_Invoice__c>)UNITY_TestDataFactory.createObject(1, UNITY_Invoice__c.getSObjectType() , invoiceFields));
                }

                Test.startTest();
                		Test.setMock(WebServiceMock.class, new AvataxCalloutMock());
                        insert invoices;

                        for(UNITY_Invoice__c invoice :invoices){
                                invoiceLIFields.put('UNITY_Invoice__c',invoice.id);
                                invoicesLI.addAll((List<UNITY_Invoice_Line_Item__c>)UNITY_TestDataFactory.createObject(1, UNITY_Invoice_Line_Item__c.getSObjectType() , invoiceLIFields));
                        }
                        insert invoicesLI;

                        // Force Invoice trigger to create SCLI, updating SC without SCLI
                        insert aux_use_for_update_without_scli;

                        for(UNITY_Invoice__c invoice :aux_use_for_update_without_scli){
                                invoice.UNITY_Invoice_Comments__c ='T';
                        }
                        
                        update aux_use_for_update_without_scli;

                Test.stopTest();
	}
}