objects/UNITY_RenderWOLiInWorkPlanPDF__mdt.object
<CustomObject>
    <fields>
        <fullName>FreeText__c</fullName>
        <label>Free Text</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoodMediumBad__c</fullName>
        <label>Good/Medium/Bad</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meter_Reading__c</fullName>
        <label>Meter Reading</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassFail__c</fullName>
        <label>Pass/Fail</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YesNo__c</fullName>
        <label>Yes/No</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <label>UNITY_RenderWOLiInWorkPlanPDF</label>
    <pluralLabel>UNITY_RenderWOLiInWorkPlanPDFs</pluralLabel>
</CustomObject>

classes/UNITY_WorkOrderLinePDFforMPController.cls
public class UNITY_WorkOrderLinePDFforMPController {
    public Id workOrderId {get; 
                           set {
                                workOrderId = value;
                               items = [SELECT Id, FSO__Order__c,LineItemNumber, Description, CreatedDate, UNITY_Render_Type__c, UNITY_Vendor_Pin__c
                                    FROM WorkOrderLineItem
                                       WHERE WorkOrderId=:workOrderId 
                                       ORDER BY Createddate ASC, FSO__Order__c ASC NULLS FIRST];
                                       
                                 //init(workOrderId);
                                
                           }}
                           
                          
     public List<WorkOrderLineItem> items {get; private set;}
      public List<UNITY_RenderWOLiInWorkPlanPDF__mdt> itemsRenderType {get; private set;}
    
     public void init(ID workOrderId) {
          items = [SELECT Id, FSO__Order__c,LineItemNumber, Description, CreatedDate, UNITY_Render_Type__c FROM WorkOrderLineItem
                                                   WHERE WorkOrderId=:workOrderId 
                                                   ORDER BY Createddate ASC, FSO__Order__c ASC NULLS FIRST];
       
          UNITY_RenderWOLiInWorkPlanPDF__mdt [] renderTypeWOLI = [SELECT FreeText__c, GoodMediumBad__c, Meter_Reading__c, PassFail__c, YesNo__c FROM UNITY_RenderWOLiInWorkPlanPDF__mdt ];
           
     }
    
}