objects/UNITY_Job_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting for scheduled job related kay value mappings for the App</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>UNITY Job Settings</label>
</CustomObject>

objects/UNITY_Vendor_Assignment__c.object
<CustomObject>
    <description>UNITY project - Cache and Log vendor assignment for work orders.</description>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Request</fullName>
                </value>
                <value>
                    <fullName>Preventive Maintenance</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Site Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Other</fullName>
                </value>
                <value>
                    <fullName>Candidate</fullName>
                </value>
                <value>
                    <fullName>Candidate-Off Hours</fullName>
                </value>
                <value>
                    <fullName>Candidate-Below Margin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Vendor Assignments</relationshipLabel>
        <relationshipName>Vendor_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2 Hour Response</fullName>
                </value>
                <value>
                    <fullName>4 Hour Response</fullName>
                </value>
                <value>
                    <fullName>12 Hour Response</fullName>
                </value>
                <value>
                    <fullName>24 Hour Response</fullName>
                </value>
                <value>
                    <fullName>48 Hour Response</fullName>
                </value>
                <value>
                    <fullName>72 Hour Response</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Planned Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Score_Factor_1__c</fullName>
        <formula>IF (ISPICKVAL(UNITY_Priority__c, &apos;2 Hour Response&apos;) || ISPICKVAL(UNITY_Priority__c, &apos;4 Hour Response&apos;),
 CASE( Status__c, &apos;Rejected-No Response&apos;, 0, 
       &apos;Accepted&apos;, 1,
       &apos;Rejected&apos;, 1,
       &apos;Rejected-Other&apos;, 1,
       NULL),
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Score Factor 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Score_Factor_2__c</fullName>
        <formula>IF (!(ISPICKVAL(UNITY_Priority__c, &apos;2 Hour Response&apos;) || ISPICKVAL(UNITY_Priority__c, &apos;4 Hour Response&apos;)),
 CASE( Status__c, &apos;Rejected-No Response&apos;, 0, 
       &apos;Accepted&apos;, 1,
       &apos;Rejected&apos;, 1,
       &apos;Rejected-Other&apos;, 1,
       NULL),
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Score Factor 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Assignments (Account)</relationshipLabel>
        <relationshipName>Vendor_Rankings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Assignment</label>
    <nameField>
        <displayFormat>VA-{0000000}</displayFormat>
        <label>Vendor Assigment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Vendor_Trade__c.object
<CustomObject>
    <description>UNITY project - Stores vendor trade coverage and attributes at trade level, such as score and price</description>
    <fields>
        <fullName>Trade__c</fullName>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Vendor Trades</relationshipLabel>
        <relationshipName>Vendor_Trades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <description>Vendor at vendor site level</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Trades</relationshipLabel>
        <relationshipName>Vendor_Trades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Trade</label>
    <nameField>
        <displayFormat>VT-{000000000}</displayFormat>
        <label>Vendor Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Trades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_VendorAssignmentScoreBatch.cls
global class UNITY_VendorAssignmentScoreBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    String query      ='SELECT {FIELDS} FROM UNITY_Vendor_Assignment__c WHERE {WHERE}';
    String fields     =' Id, ' 
                      +' Trade__c,'
                      +' Status__c,'
                      +' Vendor__c,'
                      +' Request_Type__c,'
                      +' UNITY_Priority__c,'
                      +' UNITY_Score_Factor_1__c,'
                      +' UNITY_Score_Factor_2__c';
    //String conditions =' (Last_Assigned__c >= THIS_MONTH AND Vendor__c = \'001R0000011QYrE\')';
    //String conditions = ' (Vendor__c = \'001R0000011QYrE\')';
    String conditions = '';
    
    
    private Map<String,UNITY_ScoreHandler.VendorTradeHandler> vendorIdTradeId_vendorTradeHelper = new Map<String,UNITY_ScoreHandler.VendorTradeHandler>();
    private static Map<string,UNITY_Job_Settings__c> jobSettings = UNITY_Job_Settings__c.getAll();

    DateTime tBegin, tEnd;

    global UNITY_VendorAssignmentScoreBatch() {
        String sDelayInDays, sPeriodInDays;
        Integer nDelayInDays, nPeriodInDays;

        if (jobSettings.get(UNITY_Constants.VendorScoreCalculation_DelayInDays_VA_KEY) != NULL)
            sDelayInDays = jobSettings.get(UNITY_Constants.VendorScoreCalculation_DelayInDays_VA_KEY).Value__c;
        if (sDelayInDays == null) 
            sDelayInDays = UNITY_Constants.VendorScoreCalculation_DelayInDays_DEFAULT;

        if (jobSettings.get(UNITY_Constants.VendorScoreCalculation_PeriodInDays_VA_KEY) != NULL)
            sPeriodInDays = jobSettings.get(UNITY_Constants.VendorScoreCalculation_PeriodInDays_VA_KEY).Value__c;
        if (sPeriodInDays == null) 
            sPeriodInDays = UNITY_Constants.VendorScoreCalculation_PeriodInDays_DEFAULT;

        nDelayInDays = Integer.valueOf(sDelayInDays);
        nPeriodInDays = Integer.valueOf(sPeriodInDays);

        Date today = DateTime.now().date();
        tEnd = today.addDays(- nDelayInDays); 
        tBegin = tEnd.addDays(- nPeriodInDays);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String sBegin = tBegin.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        String sEnd = tEnd.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        String sLogMsg = 'Job Started - Calculating VA Factors - From ' + sBegin + ' to ' + sEnd;
        UNITY_Utils.insertJobLog(UNITY_Constants.JOB_LOG_SEVERITY.INFO, 'VendorScoreCalcuation-VA Factors', 'Started', sLogMsg);

        if (conditions != '')
            conditions ='((Last_Assigned__c >= ' + sBegin + ' AND Last_Assigned__c < ' + sEnd + ') AND '  + conditions + ')';
        else
            conditions ='(Last_Assigned__c >= ' + sBegin + ' AND Last_Assigned__c < ' + sEnd + ')';
        
        // add fields and conditions 
        query =  query.replace('{FIELDS}',fields).replace('{WHERE}',conditions);
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {

        UNITY_Utils.insertJobLog(UNITY_Constants.JOB_LOG_SEVERITY.INFO, 'VendorScoreCalcuation-VA Factors', 'In progress', 'Calculation In Progress...');

        Set<String> accountId_tradeId = UNITY_ScoreHandler.execute( UNITY_Vendor_Assignment__c.getSObjectType() , scope, this.vendorIdTradeId_vendorTradeHelper);
        List<UNITY_Vendor_Trade__c> aux_vt =  new List<UNITY_Vendor_Trade__c>();

        for(String key :accountId_tradeId){
            if(this.vendorIdTradeId_vendorTradeHelper.get(key)!=null){
                this.vendorIdTradeId_vendorTradeHelper.get(key).calculate();
                aux_vt.add(this.vendorIdTradeId_vendorTradeHelper.get(key).vendorTrade);
            }
        }
        update aux_vt;
    }
    
    global void finish(Database.BatchableContext BC) {
        UNITY_Utils.insertJobLog(UNITY_Constants.JOB_LOG_SEVERITY.INFO, 'VendorScoreCalcuation-VA Factors', 'Completed', 'Calculation Completed');
    }
    
}