objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Account_Record_Type__c</fullName>
        <formula>IF( UNITY_Account__r.RecordType.Name = &quot;Customer&quot;, &quot;Customer&quot;, IF( (UNITY_Account__r.RecordType.Name = &quot;Vendor&quot;|| UNITY_Account__r.RecordType.Name = &quot;Miner&quot;), &quot;Vendor&quot;, &quot;&quot;))</formula>
        <label>Account Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Default_Labor_Rate__c</fullName>
        <label>Default Labor Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Has_Preferred_Part__c</fullName>
        <label>Has Preferred Part</label>
        <summaryFilterItems>
            <field>UNITY_Service_Contract_Line_Item__c.UNITY_Is_Preferred_Part__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>UNITY_Service_Contract_Line_Item__c.UNITY_Service_Contract__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UNITY_IS_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Denotes whether the Service Contract is Active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract_Line_Item__c.object
<CustomObject>
    <description>Unity project, service contract line items will capture labor and part pricing related to a specific service contract for a vendor or customer.</description>
    <fields>
        <fullName>UNITY_Labor_Cost__c</fullName>
        <description>Labor Rate</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract__c</fullName>
        <description>Unity project, master detail relationship between Service Contract and its line items</description>
        <label>Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>UNITY_Service_Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Trade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Service Contract Line Items</relationshipLabel>
        <relationshipName>Service_Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Contract Line Item</label>
    <nameField>
        <displayFormat>SCL-{0000}</displayFormat>
        <label>Service Contract Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Vendor_Trade__c.object
<CustomObject>
    <description>UNITY project - Stores vendor trade coverage and attributes at trade level, such as score and price</description>
    <fields>
        <fullName>Price_PM__c</fullName>
        <label>Price PM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Project__c</fullName>
        <label>Price Project</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_SR__c</fullName>
        <label>Price SR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_SS__c</fullName>
        <label>Price SS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Score_Project__c</fullName>
        <label>Score Project</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <label>Trade</label>
        <referenceTo>FSO__Skill__c</referenceTo>
        <relationshipLabel>Vendor Trades</relationshipLabel>
        <relationshipName>Vendor_Trades</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <description>Vendor at vendor site level</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Trades</relationshipLabel>
        <relationshipName>Vendor_Trades</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Trade</label>
    <nameField>
        <displayFormat>VT-{000000000}</displayFormat>
        <label>Vendor Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Trades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_ServiceContractHandler.cls
public with sharing class UNITY_ServiceContractHandler extends UNITY_BaseHandler{
    
    public List<Account> accountWithDeletedServiceContract = new List<Account>();
    
    private Set<id> getPricesFromSC = new Set<id>();
    
    private Set<Id> scToBeDeleted   = new Set<Id>();
    
    Map<Id, Decimal> serviceContractNewValue = new Map<Id, Decimal>();
    
    public override void bulkBefore(){
        
        /*if (trigger.isDelete){
            
            Set<Id> scToBeDeleted = new Set<Id>();
            
            for (SObject iter: trigger.old){
                
                scToBeDeleted.add(iter.Id);
            }
            
            accountWithDeletedServiceContract = [select id, UNITY_Has_Preferred_Part__c, UNITY_Service_Contract__c from Account where id in: scToBeDeleted];
        }*/
        
    }
    
    public override void bulkAfter(){
        
        if (!trigger.isDelete){
            
            //if UNITY_Has_Preferred_Part__c field has changed, update account
            for (SObject iter: trigger.new){
                
                //UNITY_Service_Contract__c oldSC = (UNITY_Service_Contract__c) iter;
                UNITY_Service_Contract__c newSC = (UNITY_Service_Contract__c) trigger.newMap.get(iter.Id);
                
               /* if (trigger.isUpdate){
                    
                    if (oldSC.UNITY_Has_Preferred_Part__c != newSC.UNITY_Has_Preferred_Part__c)serviceContractNewValue.put(newSC.Id, newSC.UNITY_Has_Preferred_Part__c);
                    
                }*/
            }
        }
    }
    
    public override void afterInsert(SObject  so){
        UNITY_Service_Contract__c newSC = (UNITY_Service_Contract__c) so;
        if( newSC.UNITY_IS_Active__c && (newSC.UNITY_Account_Record_Type__c =='Vendor')) getPricesFromSC.add(newSC.id);
    }
    
    public override void afterUpdate(SObject oldSo, SObject so){
        UNITY_Service_Contract__c oldSC = (UNITY_Service_Contract__c) oldSo;
        UNITY_Service_Contract__c newSC = (UNITY_Service_Contract__c) so;
        
        if (oldSC.UNITY_Has_Preferred_Part__c != newSC.UNITY_Has_Preferred_Part__c)serviceContractNewValue.put(newSC.Id, newSC.UNITY_Has_Preferred_Part__c);
        
        if( newSC.UNITY_IS_Active__c && (newSC.UNITY_Account_Record_Type__c =='Vendor') && (oldSC.UNITY_IS_Active__c!= newSC.UNITY_IS_Active__c) ){
                  
            getPricesFromSC.add(newSC.id);
        }
        
    }
    
    public override void afterDelete(SObject so){
        
        UNITY_Service_Contract__c oldSC = (UNITY_Service_Contract__c) so;
        
         scToBeDeleted.add(oldSC.Id);
        
    }
    
    public override void andFinally(){
                
        /*for (Account acc: accountWithDeletedServiceContract){
                
            acc.UNITY_Has_Preferred_Part__c = false;
        }
        
        List<Account> accountsToUpdate = [select id, UNITY_Service_Contract__c, UNITY_Has_Preferred_Part__c from Account where UNITY_Service_Contract__c in: serviceContractNewValue.keySet()];
        
        for (Account acc: accountsToUpdate){
            
            acc.UNITY_Has_Preferred_Part__c = serviceContractNewValue.get(acc.UNITY_Service_Contract__c) != 0;
        }
        
        accountsToUpdate.addAll(accountWithDeletedServiceContract);
        update accountsToUpdate;*/
        preferredPartHandler();
        
        updateVendorPrices();
        
    }
    
    private void preferredPartHandler(){
        
        List<Account> accountsToUpdate = new List<Account> ();
        
        if(Trigger.isDelete && (scToBeDeleted.size()>0)){
            
            accountsToUpdate = [select id, UNITY_Has_Preferred_Part__c, UNITY_Service_Contract__c from Account where id in :scToBeDeleted];
                
            for (Account acc: accountWithDeletedServiceContract){
                    
                acc.UNITY_Has_Preferred_Part__c = false;
        	}
        }
        
        if(Trigger.isUpdate && (serviceContractNewValue.size()>0)){
            
             accountsToUpdate = [select id, UNITY_Service_Contract__c, UNITY_Has_Preferred_Part__c from Account where UNITY_Service_Contract__c in: serviceContractNewValue.keySet()];
            
            for (Account acc: accountsToUpdate){
                
                acc.UNITY_Has_Preferred_Part__c = serviceContractNewValue.get(acc.UNITY_Service_Contract__c) != 0;
            }
        }
        
        if(accountsToUpdate.size()>0)update accountsToUpdate;
		
        
    }
    
    private void updateVendorPrices(){
         
 		 List<UNITY_Vendor_Trade__c> aux_vendorsTrades = new List<UNITY_Vendor_Trade__c>();
         List<UNITY_Vendor_Trade__c> aux_update_vendorsTrades = new List<UNITY_Vendor_Trade__c>();
         List<UNITY_Service_Contract__c> aux_sc = new List<UNITY_Service_Contract__c>();
         Set<id> vendorPricesToUpdate = new Set<id>();
         Map<String,Map<String,double>> vendorTrade_requestTypeRate  = new Map<String,Map<String,double>>();
         Map<String,Map<String,double>> vendor_requestTypeRate = new  Map<String,Map<String,double>>();
  
         if(getPricesFromSC.size() > 0){
             
             aux_sc = [SELECT id, 
                              UNITY_Account__c ,
                              UNITY_Default_Labor_Rate__c ,
                              RecordTypeId,
                              RecordType.Name,
                              (SELECT ID, UNITY_Labor_Cost__c, UNITY_Trade__c 
                               FROM UNITY_Service_Contract_Line_Items__r  //AND UNITY_Labor_Cost__c <> null
                               WHERE RecordTypeId = :UNITY_Constants.SCLI_HOURLY_RATE_RECORDTYPE  )
                       FROM UNITY_Service_Contract__c
                       WHERE id IN :getPricesFromSC];
             
             for(UNITY_Service_Contract__c sc :aux_sc){
                 
                 if(sc.UNITY_Service_Contract_Line_Items__r.size()>0){
                     
                     for(UNITY_Service_Contract_Line_Item__c scli :sc.UNITY_Service_Contract_Line_Items__r){
                         
                         //UNITY_Service_Contract_Line_Item__c  scli = sc.UNITY_Service_Contract_Line_Items__r.get(0);
                     
                         if(vendorTrade_requestTypeRate.get(sc.UNITY_Account__c+'-'+scli.UNITY_Trade__c) == null)
                            vendorTrade_requestTypeRate.put(sc.UNITY_Account__c+'-'+scli.UNITY_Trade__c , new Map<String,double>());
                    
                         vendorTrade_requestTypeRate.get(sc.UNITY_Account__c+'-'+scli.UNITY_Trade__c).put(
                            UNITY_Constants.WO_RECORDTYPE_ABBR.get(sc.RecordType.Name),
                            ((scli.UNITY_Labor_Cost__c==null)? sc.UNITY_Default_Labor_Rate__c: scli.UNITY_Labor_Cost__c));
                         
                         
                     }
                    // vendorPricesToUpdate.add(sc.UNITY_Account__c);
                 }else{
                     
                     if(vendor_requestTypeRate.get(sc.UNITY_Account__c) == null)
                         vendor_requestTypeRate.put(sc.UNITY_Account__c, new Map<String,double>());
                    
                     vendor_requestTypeRate.get(sc.UNITY_Account__c).put(
                         UNITY_Constants.WO_RECORDTYPE_ABBR.get(sc.RecordType.Name),
                          ((sc.UNITY_Default_Labor_Rate__c==null)? null: sc.UNITY_Default_Labor_Rate__c));
                     
                 }
                 vendorPricesToUpdate.add(sc.UNITY_Account__c);
                 
             }
             //UNITY_TestDataFactory.testLog('#### sam '+vendorTrade_requestTypeRate.keySet().size()); 
             aux_vendorsTrades = [SELECT id, name,Vendor__c, Trade__c, Price_PM__c, Price_SR__c, Price_SS__c, Score_Project__c  
                                  FROM UNITY_Vendor_Trade__c
                                  WHERE Vendor__c IN :vendorPricesToUpdate];
             
             if(aux_vendorsTrades.size() > 0){
                 
                 String vendorTradeKey = '';
                 for(UNITY_Vendor_Trade__c onVTrade :aux_vendorsTrades){
                     
                     vendorTradeKey = onVTrade.Vendor__c+'-'+onVTrade.Trade__c;
                     
                     if(vendorTrade_requestTypeRate.get(vendorTradeKey)!=null){
                         for(String onAbbr :vendorTrade_requestTypeRate.get(vendorTradeKey).keySet()){
                             if(onAbbr == 'SR') onVTrade.Price_SR__c = vendorTrade_requestTypeRate.get(vendorTradeKey).get(onAbbr) ; 
                             if(onAbbr == 'SS') onVTrade.Price_SS__c = vendorTrade_requestTypeRate.get(vendorTradeKey).get(onAbbr) ; 
                             if(onAbbr == 'Project') onVTrade.Price_Project__c = vendorTrade_requestTypeRate.get(vendorTradeKey).get(onAbbr) ; 
                             if(onAbbr == 'PM') onVTrade.Price_PM__c = vendorTrade_requestTypeRate.get(vendorTradeKey).get(onAbbr) ; 
                         }
                         aux_update_vendorsTrades.add(onVTrade);
                     }else if(vendor_requestTypeRate.get(onVTrade.Vendor__c) !=null){
                         
                         for(String onAbbr :vendor_requestTypeRate.get(onVTrade.Vendor__c).keySet()){
                             if(onAbbr == 'SR') onVTrade.Price_SR__c = vendor_requestTypeRate.get(onVTrade.Vendor__c).get(onAbbr) ; 
                             if(onAbbr == 'SS') onVTrade.Price_SS__c = vendor_requestTypeRate.get(onVTrade.Vendor__c).get(onAbbr) ; 
                             if(onAbbr == 'Project') onVTrade.Price_Project__c = vendor_requestTypeRate.get(onVTrade.Vendor__c).get(onAbbr) ; 
                             if(onAbbr == 'PM') onVTrade.Price_PM__c = vendor_requestTypeRate.get(onVTrade.Vendor__c).get(onAbbr) ; 
                         }
                         aux_update_vendorsTrades.add(onVTrade);
                     }
                 }
                 
                 update aux_update_vendorsTrades;
             }
             
         }
        
     }
    
}