objects/UNITY_Proposal__c.object
<CustomObject>
    <description>UNITY object</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Proposal_Line_Item__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Proposal__c</fullName>
        <label>Quote</label>
        <referenceTo>UNITY_Proposal__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity_Price__c</fullName>
        <formula>UNITY_Customer_Adjusted_Quantity__c * UNITY_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quantity Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QTLI-{0000000000}</displayFormat>
        <label>Proposal Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UNITY_QuoteLineItemsController.cls
/*
 * @programer: Rodrigo Birriel
 * @date:      01/27/2015
 */
public class UNITY_QuoteLineItemsController {
    public Id quoteId {get; 
                           set {
                               quoteId = value;
                               items = [SELECT Id, UNITY_Quantity_Price__c, UNITY_Description__c, UNITY_Quantity__c, UNITY_Unit_Price__c  
                                        FROM UNITY_Proposal_Line_Item__c
                                        WHERE UNITY_Proposal__c=:quoteId 
                                        ORDER BY UNITY_Proposal__c ASC NULLS FIRST];
                           }}
    
    public String totalPrice {get; set;}
    
    public List<UNITY_Proposal_Line_Item__c> items {get; set;}
    
}