objects/UNITY_MuleSiteSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mule site settings for subdmains properties.</description>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content-Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>mule domain endpoing</description>
        <label>Domain</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <label>Host</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Protocol__c</fullName>
        <defaultValue>&apos;http&apos;</defaultValue>
        <label>Protocol</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UNITY Mule Site Setting</label>
</CustomObject>

classes/UNITY_MuleSiteSettingUtils.cls
/**
 *   @programer:    Rodrigo Birriel 
 *   @description: Wrapper class to access the mule site setting.
 *   @date:         02/16/2015
 */
public class UNITY_MuleSiteSettingUtils {  
    
    public static String CUSTOMER       = 'Customer';
    public static String VENDOR         = 'Vendor';
    public static String INVOICE        = 'Invoice';
    public static String PURCHASE_ORDER = 'PurchaseOrder';
    public static String CASE1          = 'Case';
    public static String CASE_COMMENT   = 'CaseComment';
    
    public static String getEndPoint(String name) {
        String endPoint = 'temp';
        if(UNITY_MuleSiteSetting__c.getInstance(name) != null) {
            UNITY_MuleSiteSetting__c  siteSetting = UNITY_MuleSiteSetting__c.getInstance(name);
            endPoint = siteSetting.Protocol__c  + '://' + siteSetting.Host__c + siteSetting.Domain__c;
            System.debug('endPoint ---> '+endPoint);
        }
        return endPoint;
    }
    
    public static String getHost(String name) {
        System.debug('getHost ---> '+name);
        String host = 'temp';
        if(UNITY_MuleSiteSetting__c.getInstance(name) != null) {
            host = UNITY_MuleSiteSetting__c.getInstance(name).Host__c;  
        }
        return host;
    }
    
    public static String getContentType(String name) {
        String contentType = 'application/json';
        if(UNITY_MuleSiteSetting__c.getInstance(name) != null && UNITY_MuleSiteSetting__c.getInstance(name).Content_Type__c != null) {
            contentType = UNITY_MuleSiteSetting__c.getInstance(name).Content_Type__c;
        }
        return contentType;
    }
    
    public static Boolean isContentTypeJSON(String name) {
        return getContentType(name) == 'application/json';
    }
    
    public static Boolean isActive(String name) {
        return UNITY_MuleSiteSetting__c.getInstance(name) != null && UNITY_MuleSiteSetting__c.getInstance(name).IsActive__c;
    }      
        
}