objects/UNITY_Proposal__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Is_Vendor_Supply__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Proposal_Status__c</fullName>
        <label>Quote Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Quote Creation</fullName>
                </value>
                <value>
                    <fullName>Agent Review Complete</fullName>
                </value>
                <value>
                    <fullName>Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Quote Finalized</fullName>
                </value>
                <value>
                    <fullName>Ready to Send to Customer</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Proposal Amended</fullName>
                </value>
                <value>
                    <fullName>Proposal Amended &amp; Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Pending Customer Review</fullName>
                </value>
                <value>
                    <fullName>Customer Approved</fullName>
                </value>
                <value>
                    <fullName>Customer Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Proposal sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Ready to Send</fullName>
                </value>
                <value>
                    <fullName>Pending Manager Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Status__c</fullName>
        <label>Customer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Manager Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>QT-{0000000000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Proposal_Line_Item__c.object
<CustomObject>
    <description>UNITY object</description>
    <fields>
        <fullName>UNITY_Activity_Type__c</fullName>
        <description>The activity type for the quote line</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UNITY_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asset Mgmt Fees</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Destination Credit</fullName>
                </value>
                <value>
                    <fullName>Double Time Labor</fullName>
                </value>
                <value>
                    <fullName>Double Time Travel</fullName>
                </value>
                <value>
                    <fullName>Field Supplies</fullName>
                </value>
                <value>
                    <fullName>Freight - New Construction</fullName>
                </value>
                <value>
                    <fullName>Freight - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Holiday Labor</fullName>
                </value>
                <value>
                    <fullName>Holiday Travel</fullName>
                </value>
                <value>
                    <fullName>Overtime Labor</fullName>
                </value>
                <value>
                    <fullName>Overtime Travel</fullName>
                </value>
                <value>
                    <fullName>Parts - New Construction</fullName>
                </value>
                <value>
                    <fullName>Parts - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Pass Through Freight</fullName>
                </value>
                <value>
                    <fullName>Pass Through Labor</fullName>
                </value>
                <value>
                    <fullName>Pass Through Parts</fullName>
                </value>
                <value>
                    <fullName>Pass Through Rentals</fullName>
                </value>
                <value>
                    <fullName>Pass Through Tax</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Preventative Maintenance</fullName>
                </value>
                <value>
                    <fullName>Rental - Equipment</fullName>
                </value>
                <value>
                    <fullName>Rental - New Construction</fullName>
                </value>
                <value>
                    <fullName>Rental - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Service Charge</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Standard Labor</fullName>
                </value>
                <value>
                    <fullName>Standard Travel</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Vendor Double Time Labor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Cost__c</fullName>
        <label>Cost</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Is_Vendor_Supply__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if the vendor supply the part.</inlineHelpText>
        <label>Is Vendor Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_Part_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Warehouse/Truck where an inventory part is sourced from</description>
        <label>Part Location</label>
        <referenceTo>FSO__Location__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Part_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Product needs to have the Miner Record Type.</errorMessage>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Miner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Proposal_Status__c</fullName>
        <label>Proposal Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Proposal Creation</fullName>
                </value>
                <value>
                    <fullName>Proposal sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Proposal Amended</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Proposal__c</fullName>
        <label>Quote</label>
        <referenceTo>UNITY_Proposal__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Proposal_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <description>The quote line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Labor - Installation</fullName>
                </value>
                <value>
                    <fullName>Labor - Service</fullName>
                </value>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Stock Receipt (Restocking)</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Box</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Each</fullName>
                </value>
                <value>
                    <fullName>Feet</fullName>
                </value>
                <value>
                    <fullName>Hour</fullName>
                </value>
                <value>
                    <fullName>Inch</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QTLI-{0000000000}</displayFormat>
        <label>Proposal Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TEST_MSPFS_NewQuoteItemContExt.cls
@isTest
private class TEST_MSPFS_NewQuoteItemContExt {
	
	private static Account accountCustomer;
	private static Account accountVendor;
	private static List<UNITY_Service_Contract__c> serviceContractsVendor;
	private static List<UNITY_Service_Contract__c> serviceContractsCustomer;
	private static List<Contact> contacts;
	private static List<Case> cases;
	private static List<UNITY_Service_Contract__c> serviceContracts;
	private static List<WorkOrder> workOrders;
	private static List<User> technicians;
	private static UNITY_Proposal__c quote;
	private static Asset testAsset;
	private static Product2 testLaborProduct;
	private static Product2 testTravelProduct;
	private static Product2 testPartProduct;
	private static Product2 testFreightProduct;
	private static PricebookEntry testLaborPBE;
	private static PricebookEntry testTravelPBE;
	private static PricebookEntry testPartPBE;
	private static PricebookEntry testFreightPBE;
	private static FSO__Location__c location;

	static void setup() {
		
		accountCustomer = UNITY_TestDataFactory.createAccounts( 1, 'Site/Location', UNITY_Constants.ACCOUNT_CUSTOMER_RECORDTYPE ).get(0);
        accountVendor = UNITY_TestDataFactory.createAccounts( 1, 'Customer', UNITY_Constants.ACCOUNT_VENDOR_RECORDTYPE ).get(0);

        system.debug('##### accountVendor.Id: '+accountVendor.Id);

        serviceContractsVendor = UNITY_TestDataFactory.createServiceContracts( 2, accountVendor.id );
        serviceContractsCustomer = UNITY_TestDataFactory.createServiceContracts( 2, accountCustomer.Id );
        contacts = UNITY_TestDataFactory.createContacts( 2, accountCustomer.Id );
        cases = UNITY_TestDataFactory.createCases( 2, accountCustomer.Id, accountVendor.Id, contacts.get(0).Id, UNITY_Constants.CASE_SERVICE_REQUEST_RECORDTYPE );
        serviceContracts = UNITY_TestDataFactory.createServiceContracts( 1, accountCustomer.Id );
        workOrders = UNITY_TestDataFactory.createWorkOrders( 2, cases.get(0).Id,accountCustomer.Id, serviceContracts.get(0).Id, UNITY_Constants.WO_SERVICE_REQUEST_RECORDTYPE );
        
        technicians = UNITY_TestDataFactory.createUsersTechnician( 1, contacts.get(0).Id );

        testAsset = new Asset( Name = 'Test', AccountId = accountVendor.Id );
        insert testAsset;
        
        List<Product2> products = new List<Product2>();
        testLaborProduct = new Product2( Name = 'TestLaborProduct_IP', ProductCode = 'Miner-Labor', Make1__c = 'TestMake', Model__c = 'TestModel', Broad__c = 'Door',
			Group__c = 'High Speed', Type__c = 'Electrical', Family = 'Equipment', SVMXC__Product_Line__c = 'Equipment', IsActive = true, Description = 'Installed Product Test Product',
			SVMXC__Product_Cost__c = 0.00, SVMXC__Inherit_Parent_Warranty__c = true, UNITY_Status__c = 'Active', UNITY_Product_Cost__c = 0, UNITY_Unit_Of_Measure__c = 'Each',
			UNITY_Product_Type__c = 'Labor'
		);
		testTravelProduct = new Product2( Name = 'TestTravelProduct_IP', ProductCode = 'Miner-Travel', Make1__c = 'TestMake1', Model__c = 'TestModel1', Broad__c = 'Door',
			Group__c = 'High Speed', Type__c = 'Electrical', Family = 'Equipment', SVMXC__Product_Line__c = 'Equipment', IsActive = true, Description = 'Travel to job site.',
			SVMXC__Product_Cost__c = 0.00, SVMXC__Inherit_Parent_Warranty__c = true, UNITY_Status__c = 'Active', UNITY_Product_Cost__c = 0, UNITY_Unit_Of_Measure__c = 'Each',
			UNITY_Product_Type__c = 'Travel'
		);
		testPartProduct = new Product2( Name = 'TestPartProduct_IP', ProductCode = 'Miner-Part', Make1__c = 'TestMake', Model__c = 'TestModel', Broad__c = 'Door',
			Group__c = 'High Speed', Type__c = 'Electrical', Family = 'Equipment', SVMXC__Product_Line__c = 'Equipment', IsActive = true, Description = 'Door',
			SVMXC__Product_Cost__c = 0.00, SVMXC__Inherit_Parent_Warranty__c = true, UNITY_Status__c = 'Active', UNITY_Product_Cost__c = 0, UNITY_Unit_Of_Measure__c = 'Each',
			UNITY_Product_Type__c = 'Part'
		);
		testFreightProduct = new Product2( Name = 'TestFreightProduct_IP', ProductCode = 'Miner-Freight', Make1__c = 'TestMake1', Model__c = 'TestModel1', Broad__c = 'Door',
			Group__c = 'High Speed', Type__c = 'Electrical', Family = 'Equipment', SVMXC__Product_Line__c = 'Equipment', IsActive = true, Description = 'Freight',
			SVMXC__Product_Cost__c = 0.00, SVMXC__Inherit_Parent_Warranty__c = true, UNITY_Status__c = 'Active', UNITY_Product_Cost__c = 0, UNITY_Unit_Of_Measure__c = 'Each',
			UNITY_Product_Type__c = 'Freight'
		);
		products.add( testLaborProduct );
		products.add( testTravelProduct );
		products.add( testPartProduct );
		products.add( testFreightProduct );
		insert products;

		List<PricebookEntry> pBEs = new List<PricebookEntry>();
		testLaborPBE = new PricebookEntry( Product2Id = testLaborProduct.Id, Pricebook2Id = Test.getStandardPricebookId() , UnitPrice = 2, Cost__c = 1 );
		testTravelPBE = new PricebookEntry( Product2Id = testTravelProduct.Id, Pricebook2Id = Test.getStandardPricebookId() , UnitPrice = 2, Cost__c = 1 );
		testPartPBE = new PricebookEntry( Product2Id = testPartProduct.Id, Pricebook2Id = Test.getStandardPricebookId() , UnitPrice = 2, Cost__c = 1 );
		testFreightPBE = new PricebookEntry( Product2Id = testFreightProduct.Id, Pricebook2Id = Test.getStandardPricebookId() , UnitPrice = 2, Cost__c = 1 );
		pBEs.add( testLaborPBE );
		pBEs.add( testTravelPBE );
		pBEs.add( testPartPBE );
		pBEs.add( testFreightPBE );
		insert pBEs;

        location = new FSO__Location__c( FSO__Geolocation__Latitude__s = 10, FSO__Geolocation__Longitude__s = 10 );
		insert location; 

		TestDataProvider.setKeyValueStore();
	}

	@isTest 
	static void testInitializationNoLinesNoStatus() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );
		test.stopTest();

		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
		System.assertEquals( true, quoteContExt.canEdit );
	}

	@isTest 
	static void testInitializationWithLinesNoStatus() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		UNITY_Proposal_Line_Item__c newQuoteLine = new UNITY_Proposal_Line_Item__c(
			UNITY_Proposal__c = quote.Id, UNITY_Quantity__c = 1, UNITY_Activity_Type__c = 'Standard Labor', UNITY_Cost__c = 1, UNITY_Type__c = 'Labor - Service',
			UNITY_Asset__c = testAsset.Id, UNITY_Unit_Price__c = 1, UNITY_Product__c = testLaborProduct.Id, UNITY_Part_Location__c = location.Id, UNITY_Part_Source__c = accountVendor.Id
		);
		insert newQuoteLine;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );
		test.stopTest();

		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
		System.assertEquals( true, quoteContExt.canEdit );
	}

	@isTest 
	static void testInitializationWithLinesCustomerApprovedStatus() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		quote.UNITY_Proposal_Status__c = UNITY_Constants.QT_STATUS_CUSTOMER_APPROVED;
		update quote;

		UNITY_Proposal_Line_Item__c newQuoteLine = new UNITY_Proposal_Line_Item__c(
			UNITY_Proposal__c = quote.Id, UNITY_Quantity__c = 1, UNITY_Activity_Type__c = 'Standard Labor', UNITY_Cost__c = 1, UNITY_Type__c = 'Labor - Service',
			UNITY_Asset__c = testAsset.Id, UNITY_Unit_Price__c = 1, UNITY_Product__c = testLaborProduct.Id, UNITY_Part_Location__c = location.Id, UNITY_Part_Source__c = accountVendor.Id
		);
		insert newQuoteLine;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );
		test.stopTest();

		System.assertEquals( 1, ApexPages.getMessages().size() );
		System.assert( ApexPages.getMessages()[0].getDetail().contains('This Quote cannot be modified.') );
		System.assertEquals( true, quoteContExt.hasError );
		System.assertEquals( false, quoteContExt.canEdit );
	}

	@isTest 
	static void testWithoutLinesAddUncompletedLineQuickSave() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quoteContExt.doQuickSave();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 2, ApexPages.getMessages().size() );
		System.assertEquals( true, quoteContExt.hasError );
		System.assertEquals( true, quoteContExt.canEdit );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLineQuickSave() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quoteContExt.doQuickSave();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLineSaveDelLine() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quoteContExt.doSave();

		quoteContExt.deleteSel();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLineSave() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quoteContExt.doSave();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLaborLineThenProductChangeMNS() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		quote.UNITY_Business_Unit__c = 'MNS';
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testLaborProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Part_Source__c = accountVendor.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );
		quotePage.getParameters().put( 'myValue', testLaborProduct.Id );

		quoteContExt.onProductChange();
		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedTravelLineThenProductChangeMNS() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		quote.UNITY_Business_Unit__c = 'MNS';
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testTravelProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testTravelProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Part_Source__c = accountVendor.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Travel';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Travel';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedPartLineThenProductChangeMNS() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		quote.UNITY_Business_Unit__c = 'MNS';
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testPartProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testPartProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Part_Source__c = accountVendor.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Parts';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Parts - New Construction';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedFreightLineThenProductChangeMNS() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		quote.UNITY_Business_Unit__c = 'MNS';
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testFreightProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testFreightProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Part_Source__c = accountVendor.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Vendor Services';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Pass Through Freight';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLaborLineThenProductChange() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testLaborProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedTravelLineThenProductChange() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testTravelProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testTravelProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Travel';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Travel';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedPartLineThenProductChange() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testPartProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testPartProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Parts';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Part';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedFreightLineThenProductChange() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testFreightProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Product__r = testFreightProduct;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Vendor Services';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Pass Through Freight';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLineWithoutProductThenProductChange() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );

		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Vendor Services';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Pass Through Freight';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onProductChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}

	@isTest 
	static void testWithoutLinesAddCompletedLineRunWrapperMethods() {
		setup();

		test.startTest();
		quote = UNITY_TestDataFactory.createQuote( 1, cases[0].Id, workOrders[0].Id, accountCustomer.Id, UserInfo.getUserId() )[0];
		update quote;

		ApexPages.StandardController stdQuote = new ApexPages.StandardController( quote );
		MSPFS_NewQuoteItemContExt quoteContExt = new MSPFS_NewQuoteItemContExt( stdQuote );

		PageReference quotePage = Page.MSPFS_NewQuoteItem;
		Test.setCurrentPage( quotePage );


		System.assertEquals( 0, quoteContExt.quoteLines.size() );

		quoteContExt.addItem();

		quoteContExt.quoteLines[0].item.UNITY_Product__c = testLaborProduct.Id;
		quoteContExt.quoteLines[0].item.UNITY_Part_Location__c = location.Id;
		quoteContExt.quoteLines[0].item.UNITY_Type__c = 'Labor - Installation';
		quoteContExt.quoteLines[0].item.UNITY_Activity_Type__c = 'Standard Labor';
		quoteContExt.quoteLines[0].item.UNITY_Quantity__c = 1;
		quoteContExt.quoteLines[0].item.UNITY_Cost__c = 5;
		quoteContExt.quoteLines[0].item.UNITY_Is_Vendor_Supply__c = true;

		quotePage.getParameters().put( 'index', string.valueOf(quoteContExt.quoteLines[0].index) );

		quoteContExt.quoteLines[0].onCostQtyChange();
		quoteContExt.quoteLines[0].onVendorSupplyChange();

		test.stopTest();

		System.assertEquals( 1, quoteContExt.quoteLines.size() );
		System.assertEquals( 0, ApexPages.getMessages().size() );
		System.assertEquals( false, quoteContExt.hasError );
	}
}