objects/UNITY_Invoice__c.object
<CustomObject>
    <description>UNITY Invoice object</description>
    <fields>
        <fullName>UNITY_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Holds the Agent information related to the Invoice Case</description>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_Email__c</fullName>
        <description>Stores Customer email information from case</description>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer_Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service Contract of Customer. Should be copied from the Case.</description>
        <label>UNITY_Service Contract</label>
        <referenceTo>UNITY_Service_Contract__c</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Customer)</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Creation</fullName>
                    <default>true</default>
                    <label>Invoice Creation</label>
                </value>
                <value>
                    <fullName>Invoice sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Invoice Finalized</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Invoice Amended</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Original_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Original invoice if this is a regenerated invoice</description>
        <label>Original Invoice</label>
        <referenceTo>UNITY_Invoice__c</referenceTo>
        <relationshipName>RegeneratedInvoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Service_Contract_Margin_Value__c</fullName>
        <label>Service Contract Margin Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Cost__c</fullName>
        <label>Total Cost</label>
        <summarizedField>UNITY_Invoice_Line_Item__c.UNITY_Cost__c</summarizedField>
        <summaryFilterItems>
            <field>UNITY_Invoice_Line_Item__c.UNITY_Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>UNITY_Invoice_Line_Item__c.UNITY_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price (Includes Service Charge)</label>
        <summarizedField>UNITY_Invoice_Line_Item__c.UNITY_Total_Price__c</summarizedField>
        <summaryFilterItems>
            <field>UNITY_Invoice_Line_Item__c.UNITY_Excluded_from_Total__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>UNITY_Invoice_Line_Item__c.UNITY_Line_Status__c</field>
            <operation>notEqual</operation>
            <value>Cancelled</value>
        </summaryFilterItems>
        <summaryForeignKey>UNITY_Invoice_Line_Item__c.UNITY_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UNITY_Invoice_Line_Item__c.object
<CustomObject>
    <description>UNITY Invoice line items</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Product must have the Miner Record Type</errorMessage>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Miner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNITY_Activity_Type__c</fullName>
        <description>The line activity type</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UNITY_Type__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asset Mgmt Fees</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Destination Credit</fullName>
                </value>
                <value>
                    <fullName>Double Time Labor</fullName>
                </value>
                <value>
                    <fullName>Double Time Travel</fullName>
                </value>
                <value>
                    <fullName>Field Supplies</fullName>
                </value>
                <value>
                    <fullName>Freight - New Construction</fullName>
                </value>
                <value>
                    <fullName>Freight - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Holiday Labor</fullName>
                </value>
                <value>
                    <fullName>Holiday Travel</fullName>
                </value>
                <value>
                    <fullName>Overtime Labor</fullName>
                </value>
                <value>
                    <fullName>Overtime Travel</fullName>
                </value>
                <value>
                    <fullName>Parts - New Construction</fullName>
                </value>
                <value>
                    <fullName>Parts - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Pass Through Freight</fullName>
                </value>
                <value>
                    <fullName>Pass Through Labor</fullName>
                </value>
                <value>
                    <fullName>Pass Through Parts</fullName>
                </value>
                <value>
                    <fullName>Pass Through Rentals</fullName>
                </value>
                <value>
                    <fullName>Pass Through Tax</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Preventative Maintenance</fullName>
                </value>
                <value>
                    <fullName>Rental - Equipment</fullName>
                </value>
                <value>
                    <fullName>Rental - New Construction</fullName>
                </value>
                <value>
                    <fullName>Rental - Service and Remodel</fullName>
                </value>
                <value>
                    <fullName>Service Charge</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Standard Labor</fullName>
                </value>
                <value>
                    <fullName>Standard Travel</fullName>
                </value>
                <value>
                    <fullName>Use Tax</fullName>
                </value>
                <value>
                    <fullName>Vendor Double Time Labor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Adjusted_Quantity__c</fullName>
        <label>Adjusted Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Invoice_Status__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Creation</fullName>
                </value>
                <value>
                    <fullName>Invoice sent for Manager Approval</fullName>
                </value>
                <value>
                    <fullName>Discount - Approved by Manager</fullName>
                </value>
                <value>
                    <fullName>Discount - Rejected by Manager</fullName>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Returned to Agent</fullName>
                </value>
                <value>
                    <fullName>Invoice Amended</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UNITY_Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>UNITY_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UNITY_Is_Vendor_Supply__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Vendor Supply</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UNITY_PO_Price__c</fullName>
        <label>PO Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNITY_Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Tax_Code__c</fullName>
        <description>The tax code applied to the invoice line</description>
        <label>Tax Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNITY_Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNITY_Type__c</fullName>
        <description>The line type</description>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Labor - Installation</fullName>
                </value>
                <value>
                    <fullName>Labor - Service</fullName>
                </value>
                <value>
                    <fullName>Parts</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Vendor Services</fullName>
                </value>
                <value>
                    <fullName>Permits and Licenses</fullName>
                </value>
                <value>
                    <fullName>Stock Receipt (Restocking)</fullName>
                </value>
                <value>
                    <fullName>Service Fee</fullName>
                </value>
                <value>
                    <fullName>Technician</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000}</displayFormat>
        <label>Invoice Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/UNITY_Service_Contract__c.object
<CustomObject>
    <description>Unity project Service Contract object to capture contract for Customer or Vendor specific to labor, parts pricing, etc.</description>
    <fields>
        <fullName>UNITY_Margin__c</fullName>
        <label>Target Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Service Contract</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UNITY_DisputeInvoiceButtonController.cls
public class UNITY_DisputeInvoiceButtonController{

    UNITY_Invoice__c invoice {get;set;}
    UNITY_Invoice__c newInvoice {get;set;}
    Case invoiceCase;
    UNITY_Service_Contract__c sContract;
    
    public UNITY_DisputeInvoiceButtonController(ApexPages.StandardController stdController) {
        this.invoice =  this.invoice = [SELECT Id, UNITY_Original_Invoice__c, UNITY_Customer__c,UNITY_Agent__c, UNITY_Case__c, UNITY_Invoice_Status__c,
                                        (SELECT UNITY_Total_Price__c, UNITY_Cost__c, UNITY_Sales_Tax__c, UNITY_PO_Price__c, UNITY_Quantity__c,
                        			   			UNITY_Adjusted_Quantity__c, Product__c, UNITY_Tax_Code__c, UNITY_Is_Vendor_Supply__c, 
                        			   			UNITY_Activity_Type__c, UNITY_Type__c FROM Invoice_Line_Items__r)
                                        FROM UNITY_Invoice__c
                        				WHERE Id =: stdController.getRecord().Id];
        this.newInvoice = new UNITY_Invoice__c();
    }
    
    public PageReference disputeInvoice(){
        if(invoice.UNITY_Invoice_Status__c == 'Disputed'){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Invoice already in "Disputed" status');
            ApexPages.addMessage(myMsg);
            return null;
        }
        Savepoint sp;
        
        try{
        sp = Database.setSavepoint();
        invoiceCase = [SELECT Id, UNITY_Customer_Service_Contract__c, UNITY_Customer__c, UNITY_Customer__r.Account_Email__c,
                       (SELECT Id,UNITY_Original_Invoice__c FROM Invoices__r)
                       FROM Case WHERE Id =: invoice.UNITY_Case__c];
        sContract = [SELECT Id, UNITY_Margin__c FROM UNITY_Service_Contract__c WHERE Id =: invoiceCase.UNITY_Customer_Service_Contract__c];
    
        newInvoice.UNITY_Case__c = invoiceCase.Id;
        newInvoice.UNITY_Customer__c = invoice.UNITY_Customer__c;
        newInvoice.UNITY_Customer_Email__c = invoiceCase.UNITY_Customer__r.Account_Email__c;
        newInvoice.UNITY_Customer_Service_Contract__c = invoiceCase.UNITY_Customer_Service_Contract__c;
        newInvoice.UNITY_Service_Contract_Margin_Value__c = sContract.UNITY_Margin__c;
        newInvoice.UNITY_Original_Invoice__c = invoice.id;
        newInvoice.UNITY_Agent__c = invoice.UNITY_Agent__c;
        //newInvoice.Name = invoice.Name + '-CR'; field is not writeable
        insert newInvoice;
        

        invoice.UNITY_Invoice_Status__c = 'Disputed';
        update invoice;
        
        // build the hierarchy map
        Map<Id,Id> invoicesMap = new Map<Id,Id>();
        for(UNITY_Invoice__c invoice : invoiceCase.Invoices__r) {
            invoicesMap.put(invoice.Id, invoice.UNITY_Original_Invoice__c);
        }
		Id topOriginalInvoiceId = invoice.Id;
        while(invoicesMap.get(topOriginalInvoiceId) != null){
       		topOriginalInvoiceId = invoicesMap.get(topOriginalInvoiceId);   
        }
        List<Order> orders = [SELECT Id, UNITY_Invoice__c, UNITY_Updated_Invoice__c, (SELECT Id, UNITY_Is_Vendor_Supply__c, UNITY_Activity_Type__c, UNITY_Type__c,UNITY_Sales_Tax__c, OrderId, UNITY_Tax_Code__c, UNITY_Price__c, UNITY_Total_Cost__c, UNITY_Total_Price__c,PricebookEntry.Product2Id, PricebookEntry.Product2.UNITY_Product_Type__c, Quantity, UNITY_Customer_Adjusted_Quantity__c FROM OrderItems) FROM Order WHERE UNITY_Invoice__c =: topOriginalInvoiceId];
        if(orders.size() == 0 && invoice.UNITY_Original_Invoice__c == null){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Invoice is not assigned to the order');
            ApexPages.addMessage(myMsg);
            return null;
        }
            
        //if(orders.size() > 1){
        //    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Invoice is assigned to more than one order');
        //    ApexPages.addMessage(myMsg);
        //    return null;
        //}
        
        List<UNITY_Invoice_Line_Item__c> invoiceLineItems = new List<UNITY_Invoice_Line_Item__c>();              

        for (Order currentOrder : orders){
            
            currentOrder.UNITY_Updated_Invoice__c = newInvoice.Id;
            currentOrder.Status = 'Invoice Regenerated';
            
        }
        for(UNITY_Invoice_Line_Item__c originalLineItem : this.invoice.Invoice_Line_Items__r) {
            UNITY_Invoice_Line_Item__c ili = new UNITY_Invoice_Line_Item__c();
            ili.UNITY_Invoice__c = newInvoice.Id;
            ili.UNITY_Total_Price__c = originalLineItem.UNITY_Total_Price__c;
            ili.UNITY_Cost__c = originalLineItem.UNITY_Cost__c;
            ili.UNITY_Sales_Tax__c = originalLineItem.UNITY_Sales_Tax__c;
            ili.UNITY_PO_Price__c = originalLineItem.UNITY_PO_Price__c; 
            ili.UNITY_Quantity__c = originalLineItem.UNITY_Quantity__c;
            ili.UNITY_Adjusted_Quantity__c = originalLineItem.UNITY_Adjusted_Quantity__c;
            ili.Product__c = originalLineItem.Product__c;
            ili.UNITY_Tax_Code__c = originalLineItem.UNITY_Tax_Code__c;
            ili.UNITY_Is_Vendor_Supply__c = originalLineItem.UNITY_Is_Vendor_Supply__c;
            ili.UNITY_Activity_Type__c = originalLineItem.UNITY_Activity_Type__c;
            ili.UNITY_Type__c = originalLineItem.UNITY_Type__c;
            invoiceLineItems.add(ili);
        }
            
            
        insert invoiceLineItems;
        update orders;
        
        PageReference pageRef = new PageReference('/' + newInvoice.Id);
        return pageRef;
        
        } catch (Exception ex){
            Database.rollback(sp);
            throw ex;
        } 
    }
}