objects/UNITY_Push_Notification__c.object
<CustomObject>
    <description>Object to hold notifications and alerts to be displayed on Service Console</description>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message on the notification. (Optional if type is not &quot;Alert&quot;).</description>
        <inlineHelpText>The message on the notification. (Optional if type is not &quot;Alert&quot;).</inlineHelpText>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>The id for the record the notification is about</description>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <description>The Name of the record this notification is about</description>
        <label>Record Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>The notification subject</description>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <description>The subscriber to get the notification. Must be a user id or a queue/group id.</description>
        <externalId>true</externalId>
        <inlineHelpText>The subscribers to this notifications. Must be a user id or a queue/group id.</inlineHelpText>
        <label>Subscriber</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of notification</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alert</fullName>
                </value>
                <value>
                    <fullName>Case Escalation</fullName>
                </value>
                <value>
                    <fullName>Emergency Case</fullName>
                </value>
                <value>
                    <fullName>Message</fullName>
                </value>
                <value>
                    <fullName>Tech Check-Out</fullName>
                </value>
                <value>
                    <fullName>Tech Onsite</fullName>
                </value>
                <value>
                    <fullName>Work Order Escalation</fullName>
                </value>
                <value>
                    <fullName>Work Order Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Push Notification</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UNITY_Push_Notification_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting defines a query and what fields to display per Push Notification type.</description>
    <fields>
        <fullName>BG_Color__c</fullName>
        <label>BG Color</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fields_Order__c</fullName>
        <description>The order in which to display the fields on the notification.</description>
        <label>Fields Order</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>The object this refers to</description>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <description>The Query to be performed in order to get the desired info per notification. All the way up to &apos;FROM Objert_Api__c&apos;. No WHERE statement included.</description>
        <inlineHelpText>The Query to be performed in order to get the desired info per notification.</inlineHelpText>
        <label>Query</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Push Notification Setting</label>
</CustomObject>

classes/UNITY_ConsoleNotificationController_UT.cls
/**This class is the test class for UNITY_ConsoleNotificationController.cls
 * @programmer: Izay Ramos-Irizarry
 * @description: This class is the test class for UNITY_ConsoleNotificationController.cls
 * @date: 3/8/2016
 * @version: 1.0
 */
@isTest
public class UNITY_ConsoleNotificationController_UT {
    /**This method tests the subscribe method in UNITY_ConsoleNotificationController.cls
     */
    public static TestMethod void testSubscribe(){
        //Create a test user
        User u = TestDataProvider.getUsers(1)[0];
        u.Ignore_Validations__c = true;
        insert u;
        //create a queue
        Group q = new Group(Name = 'Test Queue',Type = 'Queue');
        insert q;
        //Create a queue object
        QueueSObject qso = new QueueSObject(QueueID = q.id, SobjectType = 'Case');
        insert qso;
        //create a regular group
        Group g = new Group(
            Name = 'Text Queue',
            Type = 'Regular'
        );
        insert g;
        //Add the curremt user to the regular group
        GroupMember gm = new GroupMember(
            GroupId = g.Id,
            UserOrGroupId = u.Id
        );
        insert gm;
        //Add the regular group to the queue
        GroupMember qm = new GroupMember(
            GroupId = q.Id,
            UserOrGroupId = g.Id
        );
        insert qm;
        //Call the subscribe method as the user u
        System.runAs(u){
            //Create a push notification setting for type Emergency case
            UNITY_Push_Notification_Setting__c pns = new UNITY_Push_Notification_Setting__c(
                Name = 'Emergency Case',
                BG_Color__c = '#ee3333',
                Object__c = 'Case',
                Query__c = 'Id,CaseNumber,Subject,OwnerId,Priority,Status,CreatedDate FROM Case',
                Fields_Order__c = '[{"Subject":"Subject"},{"Priority":"Priority"},{"Created":"CreatedDate"}]'
            );
            insert pns;
            //Create an account and a contact
            Account a = TestDataProvider.getAccounts(1, 'Customer', 'Customer')[0];
            insert a;
            Contact c = TestDataProvider.getContacts(1, a.id)[0];
            insert c;
            //Create a case to relate a notification to
            Case mycase = new Case(
                Subject = 'Test Notification Case',
                Description = 'Test case Description',
                ContactId = c.Id
            );
            insert mycase;
            Test.startTest();
            String result = UNITY_ConsoleNotificationController.subscribe();
            System.debug('result: ' + result);
            System.assert(result.indexOf('"success":true') != -1);
            //Call the subscribe method again to cover the update
            result = UNITY_ConsoleNotificationController.subscribe();
            System.assert(result.indexOf('"success":true') != -1);
            //Create a notification record type Alert
            UNITY_Push_Notification__c upn1 = new UNITY_Push_Notification__c(
                Message__c = 'Test Message',
                Record_Id__c = '',
                Record_Name__c = '',
                Subject__c = 'Test Notification',
                Subscriber__c = u.Id,
                Type__c = 'Alert'
            );
            insert upn1;
            List<UNITY_ConsoleNotificationController.Notif> resultNotif = UNITY_ConsoleNotificationController.getNotification(upn1.Id);
            //Create a notification record type Emergency Case
            UNITY_Push_Notification__c upn2 = new UNITY_Push_Notification__c(
                Message__c = 'Test Message',
                Record_Id__c = mycase.Id,
                Record_Name__c = myCase.CaseNumber,
                Subject__c = 'Test Notification',
                Subscriber__c = u.Id,
                Type__c = 'Emergency Case'
            );
            insert upn2;
            resultNotif = UNITY_ConsoleNotificationController.getNotification(upn2.Id);
            //Create a notification record type Emergency Case
            UNITY_Push_Notification__c upn3 = new UNITY_Push_Notification__c(
                Message__c = 'Test Message. Alert with record id',
                Record_Id__c = mycase.Id,
                Record_Name__c = myCase.CaseNumber,
                Subject__c = 'Test Notification',
                Subscriber__c = u.Id,
                Type__c = 'Alert'
            );
            insert upn3;
            resultNotif = UNITY_ConsoleNotificationController.getNotification(upn3.Id);
            //Create a notification record type Emergency Case
            UNITY_Push_Notification__c upn4 = new UNITY_Push_Notification__c(
                Message__c = 'Test Message. Other than Alert without record id',
                Record_Id__c = null,
                Record_Name__c = null,
                Subject__c = 'Test Notification',
                Subscriber__c = u.Id,
                Type__c = 'Emergency Case'
            );
            insert upn4;
            resultNotif = UNITY_ConsoleNotificationController.getNotification(upn4.Id);
            List<UNITY_ConsoleNotificationController.Notif> resultList = UNITY_ConsoleNotificationController.getMyNotifs();
            Test.stopTest();
        }
    }
}